<?php
declare(strict_types=1);
header('X-Content-Type-Options: nosniff');header('X-Frame-Options: SAMEORIGIN');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');
$path=rawurldecode(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)??'/');
if(str_contains($path,'..')||str_contains($path,"\0")||str_contains($path,'\\')){http_response_code(404);exit;}
if(preg_match('~^/(assets/floralis/|uploads/|assets/)[a-zA-Z0-9_.\/-]+$~',$path)){
 $candidate=str_starts_with($path,'/assets/floralis/')||str_starts_with($path,'/uploads/')?__DIR__.'/public'.$path:__DIR__.'/dist'.$path;
 $ext=strtolower(pathinfo($candidate,PATHINFO_EXTENSION));$types=['js'=>'text/javascript','css'=>'text/css','woff2'=>'font/woff2','woff'=>'font/woff','png'=>'image/png','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','webp'=>'image/webp','svg'=>'image/svg+xml','mp4'=>'video/mp4'];
 if(!is_file($candidate)||!isset($types[$ext])){http_response_code(404);exit;}
 header('Content-Type: '.$types[$ext]);header('Cache-Control: public, max-age=3600');$size=filesize($candidate);$start=0;$end=$size-1;
 if($ext==='mp4'){header('Accept-Ranges: bytes');if(isset($_SERVER['HTTP_RANGE'])&&preg_match('/bytes=(\d+)-(\d*)/',$_SERVER['HTTP_RANGE'],$range)){$start=(int)$range[1];$end=$range[2]!==''?min((int)$range[2],$end):$end;if($start>$end){http_response_code(416);exit;}http_response_code(206);header("Content-Range: bytes $start-$end/$size");}}
 header('Content-Length: '.($end-$start+1));$f=fopen($candidate,'rb');fseek($f,$start);$left=$end-$start+1;while($left>0&&!feof($f)){$b=fread($f,min(65536,$left));echo $b;$left-=strlen($b);}fclose($f);exit;
}
require __DIR__.'/app/bootstrap.php';
if(str_starts_with($path,'/api/')){if((int)($_SERVER['CONTENT_LENGTH']??0)>9*1024*1024)respond(['error'=>'Cerere prea mare.'],413);require __DIR__.'/app/api.php';exit;}
function escape(string $s): string {return htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$base=rtrim(env('APP_URL','http://localhost:5173'),'/');
if($path==='/robots.txt'){header('Content-Type: text/plain');echo "User-agent: *\nDisallow: /admin\nDisallow: /api\nDisallow: /cont\nDisallow: /cos\nDisallow: /checkout\nDisallow: /comanda\nDisallow: /favorite\nSitemap: $base/sitemap.xml\n";exit;}
if($path==='/sitemap.xml'){header('Content-Type: application/xml; charset=utf-8');$urls=['/','/magazin','/decor-floral','/despre-noi','/contact','/galerie','/blog','/faq'];foreach(all("SELECT slug,seo FROM products WHERE status='publish'") as $p)if(empty(decoded($p['seo'])['noindex']))$urls[]='/produs/'.$p['slug'];foreach(categories() as $c)if(empty($c['seo']['noindex']))$urls[]='/categorie/'.$c['slug'];foreach(all("SELECT slug,seo FROM pages WHERE status='publish'") as $p)if(empty(decoded($p['seo'])['noindex']))$urls[]='/'.$p['slug'];echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach(array_unique($urls) as $url)echo '<url><loc>'.escape($base.$url).'</loc></url>';echo '</urlset>';exit;}
if(!is_file(__DIR__.'/dist/index.html')){http_response_code(503);echo '<!doctype html><html lang="ro"><meta charset="utf-8"><h1>Floralis — pregătire locală</h1><p>Compilează interfața cu npm run build, apoi reîncarcă pagina.</p></html>';exit;}
$settings=settingAll();$title='Floralis — arta florilor';$desc=$settings['hero_text']??'';$canonical=$base.($path==='/'?'/':$path);$image=$settings['hero_image']??'/assets/floralis/logo.png';$private=(bool)preg_match('~^/(admin|cont|cos|checkout|comanda|favorite)~',$path)||!empty($_GET);$structured=[];$snapshot='';$seo=[];
$titles=['/magazin'=>'Magazin','/decor-floral'=>'Decor floral','/despre-noi'=>'Povestea noastră','/contact'=>'Contact','/galerie'=>'Galerie','/blog'=>'Din atelier','/faq'=>'Întrebări frecvente','/favorite'=>'Favorite','/cos'=>'Coșul tău','/checkout'=>'Finalizare comandă'];
if(isset($titles[$path]))$title=$titles[$path].' · Floralis';
if(preg_match('~^/produs/([^/]+)$~',$path,$m)){$p=one("SELECT * FROM products WHERE slug=? AND status='publish'",[$m[1]]);if(!$p){http_response_code(404);$title='Produsul nu a fost găsit · Floralis';$private=true;}else{$p=product($p);$title=$p['name'].' · Floralis';$desc=$p['short_description']?:$p['description'];$image=$p['images'][0]['url']??$image;$seo=$p['seo'];$structured[]=['@context'=>'https://schema.org','@type'=>'Product','name'=>$p['name'],'sku'=>$p['sku'],'image'=>$base.$image,'description'=>$desc,'offers'=>['@type'=>'Offer','url'=>$canonical,'priceCurrency'=>'RON','price'=>$p['price_cents']/100,'availability'=>'https://schema.org/'.($p['stock_status']==='instock'&&(!$p['manage_stock']||$p['stock']>0)?'InStock':'OutOfStock')]];$snapshot='<article><h1>'.escape($p['name']).'</h1><img src="'.escape($image).'" alt="'.escape($p['name']).'"><p>'.escape($desc).'</p><p>'.escape((string)($p['price_cents']/100)).' lei</p></article>';}}
elseif(preg_match('~^/categorie/([^/]+)$~',$path,$m)){$c=one('SELECT * FROM categories WHERE slug=?',[$m[1]]);if(!$c){http_response_code(404);$private=true;}else{$title=$c['name'].' · Floralis';$desc=$c['description'];$image=$c['image'];$seo=decoded($c['seo']);}}
else{$p=one("SELECT * FROM pages WHERE slug=? AND status='publish'",[trim($path,'/')]);if($p){$title=$p['title'].' · Floralis';$desc=substr($p['body'],0,250);$seo=decoded($p['seo']);if($p['image'])$image=$p['image'];$snapshot='<article><h1>'.escape($p['title']).'</h1><div>'.nl2br(escape($p['body'])).'</div></article>';}elseif(!isset($titles[$path])&&$path!=='/'&&!preg_match('~^/(admin|cont|comanda)(/|$)~',$path)){http_response_code(404);$private=true;$title='Pagina nu a fost găsită · Floralis';}}
if(!empty($seo['title']))$title=$seo['title'];if(!empty($seo['description']))$desc=$seo['description'];if(!empty($seo['canonical']))$canonical=$seo['canonical'];if(!empty($seo['og_image']))$image=$seo['og_image'];$private=$private||!empty($seo['noindex']);
$structured[]=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'Floralis — arta florilor','url'=>$base,'logo'=>$base.'/assets/floralis/logo.png','telephone'=>$settings['phone'],'email'=>$settings['email'],'address'=>['@type'=>'PostalAddress','streetAddress'=>$settings['address'],'addressCountry'=>'RO']];
if($path!=='/')$structured[]=['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Acasă','item'=>$base.'/'],['@type'=>'ListItem','position'=>2,'name'=>$title,'item'=>$canonical]]];
if($path==='/faq')$structured[]=['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>[['@type'=>'Question','name'=>'Cum solicit un decor pentru un eveniment?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Decorurile pentru nunți și botezuri sunt realizate pe bază de comandă. Contactează-ne pentru a stabili împreună stilul, florile și bugetul.']],['@type'=>'Question','name'=>'Pot exista diferențe față de fotografie?','acceptedAnswer'=>['@type'=>'Answer','text'=>'În funcție de stoc și sezon, produsele pot suferi mici modificări, însă cromatica va fi păstrată.']]]];
$meta='<meta name="description" content="'.escape(substr($desc,0,350)).'"><link rel="canonical" href="'.escape($canonical).'"><meta name="robots" content="'.($private?'noindex,nofollow':'index,follow').'"><meta property="og:type" content="website"><meta property="og:title" content="'.escape($title).'"><meta property="og:description" content="'.escape(substr($desc,0,350)).'"><meta property="og:url" content="'.escape($canonical).'"><meta property="og:image" content="'.escape(str_starts_with($image,'http')?$image:$base.$image).'"><meta name="twitter:card" content="summary_large_image">';
foreach($structured as $item)$meta.='<script type="application/ld+json">'.json_encode($item,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE).'</script>';
$html=file_get_contents(__DIR__.'/dist/index.html');$html=preg_replace('~<title>.*?</title>~s','<title>'.escape($title).'</title>',$html);$html=str_replace('<!--SEO-->',$meta,$html);if($snapshot)$html=str_replace('<div id="root"></div>','<div id="root"><div class="seo-snapshot">'.$snapshot.'</div></div>',$html);echo $html;
