<?php
declare(strict_types=1);
header('X-Content-Type-Options: nosniff');header('X-Frame-Options: SAMEORIGIN');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');
$path=rawurldecode(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)??'/');
if(str_contains($path,'..')||str_contains($path,"\0")||str_contains($path,'\\')){http_response_code(404);exit;}
if(preg_match('~^/(assets/floralis/|uploads/|assets/)[a-zA-Z0-9_.\/-]+$~',$path)){
 $candidate=str_starts_with($path,'/assets/floralis/')||str_starts_with($path,'/uploads/')?__DIR__.'/public'.$path:__DIR__.'/dist'.$path;
 $ext=strtolower(pathinfo($candidate,PATHINFO_EXTENSION));$types=['js'=>'text/javascript','css'=>'text/css','woff2'=>'font/woff2','woff'=>'font/woff','png'=>'image/png','jpg'=>'image/jpeg','jpeg'=>'image/jpeg','webp'=>'image/webp','svg'=>'image/svg+xml','mp4'=>'video/mp4'];
 if(!is_file($candidate)||!isset($types[$ext])){http_response_code(404);exit;}
 header('Content-Type: '.$types[$ext]);header('Cache-Control: public, max-age=3600');$size=filesize($candidate);$start=0;$end=$size-1;
 if($ext==='mp4'){header('Accept-Ranges: bytes');if(isset($_SERVER['HTTP_RANGE'])&&preg_match('/bytes=(\d+)-(\d*)/',$_SERVER['HTTP_RANGE'],$range)){$start=(int)$range[1];$end=$range[2]!==''?min((int)$range[2],$end):$end;if($start>$end){http_response_code(416);exit;}http_response_code(206);header("Content-Range: bytes $start-$end/$size");}}
 header('Content-Length: '.($end-$start+1));$f=fopen($candidate,'rb');fseek($f,$start);$left=$end-$start+1;while($left>0&&!feof($f)){$b=fread($f,min(65536,$left));echo $b;$left-=strlen($b);}fclose($f);exit;
}
require __DIR__.'/app/bootstrap.php';
if(str_starts_with($path,'/api/')){if((int)($_SERVER['CONTENT_LENGTH']??0)>9*1024*1024)respond(['error'=>'Cerere prea mare.'],413);require __DIR__.'/app/api.php';exit;}
function escape(string $s): string {return htmlspecialchars($s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function xmlEscape(string $s): string {return htmlspecialchars($s,ENT_QUOTES|ENT_XML1|ENT_SUBSTITUTE,'UTF-8');}
function absoluteUrl(string $base,string $url): string {return preg_match('~^https?://~i',$url)?$url:$base.'/'.ltrim($url,'/');}
$base=rtrim(env('APP_URL','http://localhost:5173'),'/');
if($path==='/robots.txt'){header('Content-Type: text/plain');echo "User-agent: *\nDisallow: /admin\nDisallow: /api\nDisallow: /cont\nDisallow: /cos\nDisallow: /checkout\nDisallow: /comanda\nDisallow: /favorite\nSitemap: $base/sitemap.xml\n";exit;}

if(in_array($path,['/llms.txt','/llms-full.txt','/agents.md'])){header('Content-Type: text/plain; charset=utf-8');echo "# Floralis — arta florilor\n\n".$base."\n\nMagazin de flori, aranjamente și decor floral. Limbă: română. Monedă: RON.\n";foreach(categories() as $c)echo "- ".$c['name'].": ".$base.'/categorie/'.$c['slug']."\n";if($path==='/llms-full.txt')foreach(all("SELECT name,slug,price_cents,stock_status FROM products WHERE status='publish'") as $p)echo "- ".$p['name'].': '.$base.'/produs/'.$p['slug'].($p['price_cents']===null?'':' | '.($p['price_cents']/100).' RON')." | ".$p['stock_status']."\n";echo "\nContact: ".settingAll()['email']."\n";exit;}

if($path==='/sitemap.xml'){
 header('Content-Type: application/xml; charset=utf-8');$urls=[];$add=function(string $url,array $data=[])use(&$urls):void{$urls[$url]=['path'=>$url,...$data];};foreach(['/','/magazin','/decor-floral','/despre-noi','/contact','/galerie','/blog','/faq'] as $url)$add($url);
 foreach(all("SELECT p.slug,p.name,p.created_at,pi.url image,pi.alt image_alt FROM products p LEFT JOIN product_images pi ON pi.id=(SELECT i.id FROM product_images i WHERE i.product_id=p.id ORDER BY i.sort_order,i.id LIMIT 1) WHERE p.status='publish' ORDER BY p.id") as $p)$add('/produs/'.$p['slug'],['lastmod'=>substr((string)$p['created_at'],0,10),'image'=>$p['image']??'','image_alt'=>($p['image_alt']??'')?:$p['name']]);
 foreach(categories() as $c)if(empty($c['seo']['noindex']))$add('/categorie/'.$c['slug'],['image'=>$c['image']??'','image_alt'=>$c['name']]);foreach(all("SELECT slug,seo,type,image FROM pages WHERE status='publish'") as $p)if(empty(decoded($p['seo'])['noindex']))$add(($p['type']==='post'?'/blog/':'/').$p['slug'],['image'=>$p['image']??'','image_alt'=>$p['slug']]);
 echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">';foreach($urls as $entry){echo '<url><loc>'.xmlEscape($base.$entry['path']).'</loc>';if(!empty($entry['lastmod']))echo '<lastmod>'.xmlEscape($entry['lastmod']).'</lastmod>';if(!empty($entry['image']))echo '<image:image><image:loc>'.xmlEscape(absoluteUrl($base,$entry['image'])).'</image:loc><image:title>'.xmlEscape($entry['image_alt']).'</image:title></image:image>';echo '</url>';}echo '</urlset>';exit;
}
if(!is_file(__DIR__.'/dist/index.html')){http_response_code(503);echo '<!doctype html><html lang="ro"><meta charset="utf-8"><h1>Floralis — pregătire locală</h1><p>Compilează interfața cu npm run build, apoi reîncarcă pagina.</p></html>';exit;}
$settings=settingAll();$title=($settings['seo_title']??'')?:'Floralis — arta florilor';$desc=($settings['seo_description']??'')?:'Aranjamente florale premium, create cu pasiune pentru cele mai frumoase momente din viața ta.';$canonical=$base.($path==='/'?'/':$path);$image=($settings['seo_og_image']??'')?:'/assets/floralis/hero-desktop.webp';$imageAlt='Floralis — arta florilor';$private=(bool)preg_match('~^/(admin|cont|cos|checkout|comanda|favorite)~',$path)||!empty($_GET);$structured=[];$snapshot='';$seo=[];$productPage=false;$productData=null;
$titles=['/magazin'=>'Magazin','/decor-floral'=>'Decor floral','/despre-noi'=>'Povestea noastră','/contact'=>'Contact','/galerie'=>'Galerie','/blog'=>'Din atelier','/faq'=>'Întrebări frecvente','/favorite'=>'Favorite','/cos'=>'Coșul tău','/checkout'=>'Finalizare comandă'];
if(isset($titles[$path]))$title=$titles[$path].' · Floralis';
if(preg_match('~^/produs/([^/]+)$~',$path,$m)){$p=one("SELECT * FROM products WHERE slug=? AND status='publish'",[$m[1]]);if(!$p){http_response_code(404);$title='Produsul nu a fost găsit · Floralis';$private=true;}else{$p=product($p);$productPage=true;$productData=$p;$title=$p['name'].' | Floralis';$desc=$p['short_description']?:$p['description'];$image=$p['images'][0]['url']??$image;$imageAlt=($p['images'][0]['alt']??'')?:$p['name'];$seo=$p['seo'];$snapshot='<article><h1>'.escape($p['name']).'</h1><img src="'.escape($image).'" alt="'.escape($imageAlt).'"><p>'.escape(metaText($desc)).'</p><p>'.($p['price_cents']===null?'Preț la cerere':escape((string)($p['price_cents']/100)).' lei').'</p></article>';}}
elseif(preg_match('~^/categorie/([^/]+)$~',$path,$m)){$c=one('SELECT * FROM categories WHERE slug=? AND visible=1',[$m[1]]);if(!$c||!in_array($c['id'],array_column(categories(),'id'))){http_response_code(404);$private=true;}else{$title=$c['name'].' · Floralis';$desc=$c['description'];$image=$c['image'];$seo=decoded($c['seo']);}}
else{$p=one("SELECT * FROM pages WHERE slug=? AND status='publish'",[str_starts_with($path,'/blog/')?substr($path,6):trim($path,'/')]);if($p){$title=$p['title'].' · Floralis';$desc=mb_substr($p['body'],0,250);$seo=decoded($p['seo']);if($p['image'])$image=$p['image'];$snapshot='<article><h1>'.escape($p['title']).'</h1><div>'.nl2br(escape($p['body'])).'</div></article>';}elseif(!isset($titles[$path])&&$path!=='/'&&!preg_match('~^/(admin|cont|comanda)(/|$)~',$path)){http_response_code(404);$private=true;$title='Pagina nu a fost găsită · Floralis';}}

if(!$snapshot&&!$private&&(in_array($path,['/','/magazin'])||str_starts_with($path,'/categorie/'))){
 $heading=$path==='/'?'Mai mult decât flori, emoții în dar.':str_replace(' · Floralis','',$title);$snapshot='<main><h1>'.escape($heading).'</h1><p>'.escape($desc).'</p><nav>';
 foreach(categories() as $c)$snapshot.='<a href="/categorie/'.escape($c['slug']).'">'.escape($c['name']).'</a> ';
 $snapshot.='</nav><section>';if(isset($c)&&str_starts_with($path,'/categorie/')&&isset($m[1]))$rows=all("SELECT p.* FROM products p JOIN product_categories pc ON pc.product_id=p.id JOIN categories c ON c.id=pc.category_id WHERE p.status='publish' AND c.slug=? LIMIT 24",[$m[1]]);else $rows=all("SELECT * FROM products WHERE status='publish' ORDER BY featured DESC,id LIMIT 24");
 foreach($rows as $row)$snapshot.='<article><a href="/produs/'.escape($row['slug']).'"><h2>'.escape($row['name']).'</h2></a><p>'.($row['price_cents']===null?'Preț la cerere':escape(number_format($row['price_cents']/100,2)).' RON').'</p></article>';
 $snapshot.='</section></main>';
}

if(!empty($seo['title']))$title=$seo['title'];if(!empty($seo['description']))$desc=$seo['description'];if(!empty($seo['canonical']))$canonical=$seo['canonical'];if(!empty($seo['og_image'])&&!$productPage)$image=$seo['og_image'];$private=$private||(!$productPage&&!empty($seo['noindex']));if($productPage&&$productData){$canonical=$base.'/produs/'.$productData['slug'];$private=false;$productImages=array_values(array_map(fn($item)=>absoluteUrl($base,$item['url']),$productData['images']));$structured[]=['@context'=>'https://schema.org','@type'=>'Product','name'=>$productData['name'],'url'=>$canonical,'sku'=>$productData['sku'],'brand'=>['@type'=>'Brand','name'=>'Floralis'],'image'=>$productImages,'description'=>metaText($desc),...($productData['categories']?['category'=>$productData['categories'][count($productData['categories'])-1]['name']]:[]),...($productData['price_cents']===null?[]:['offers'=>['@type'=>'Offer','url'=>$canonical,'priceCurrency'=>'RON','price'=>number_format($productData['price_cents']/100,2,'.',''),'itemCondition'=>'https://schema.org/NewCondition','availability'=>'https://schema.org/'.($productData['stock_status']==='instock'&&(!$productData['manage_stock']||$productData['stock']>0)?'InStock':'OutOfStock'),'seller'=>['@type'=>'Organization','name'=>'Floralis — arta florilor']]])];}
$structured[]=['@context'=>'https://schema.org','@type'=>'Organization','name'=>'Floralis — arta florilor','url'=>$base,'logo'=>$base.'/assets/floralis/logo.png','telephone'=>$settings['phone'],'email'=>$settings['email'],'address'=>['@type'=>'PostalAddress','streetAddress'=>$settings['address'],'addressCountry'=>'RO']];
if($path!=='/')$structured[]=['@context'=>'https://schema.org','@type'=>'BreadcrumbList','itemListElement'=>[['@type'=>'ListItem','position'=>1,'name'=>'Acasă','item'=>$base.'/'],['@type'=>'ListItem','position'=>2,'name'=>$title,'item'=>$canonical]]];
if($path==='/faq')$structured[]=['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>[['@type'=>'Question','name'=>'Cum solicit un decor pentru un eveniment?','acceptedAnswer'=>['@type'=>'Answer','text'=>'Decorurile pentru nunți și botezuri sunt realizate pe bază de comandă. Contactează-ne pentru a stabili împreună stilul, florile și bugetul.']],['@type'=>'Question','name'=>'Pot exista diferențe față de fotografie?','acceptedAnswer'=>['@type'=>'Answer','text'=>'În funcție de stoc și sezon, produsele pot suferi mici modificări, însă cromatica va fi păstrată.']]]];
$title=metaText($title);$desc=metaExcerpt($desc,160);$imageUrl=absoluteUrl($base,$image);$imageType=['jpg'=>'image/jpeg','jpeg'=>'image/jpeg','png'=>'image/png','webp'=>'image/webp'][strtolower(pathinfo(parse_url($imageUrl,PHP_URL_PATH)??'',PATHINFO_EXTENSION))]??'';$imageSize=null;$localImage=parse_url($imageUrl,PHP_URL_PATH);if(is_string($localImage)&&preg_match('~^/(assets/floralis/|uploads/)[a-zA-Z0-9_.\/-]+$~',$localImage)){$_imageFile=__DIR__.'/public'.$localImage;if(is_file($_imageFile))$imageSize=@getimagesize($_imageFile);}
$meta='<meta name="description" content="'.escape($desc).'"><link rel="canonical" href="'.escape($canonical).'"><meta name="robots" content="'.($private?'noindex,nofollow':'index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1').'"><meta property="og:locale" content="ro_RO"><meta property="og:site_name" content="Floralis — arta florilor"><meta property="og:type" content="'.($productPage?'product':'website').'"><meta property="og:title" content="'.escape($title).'"><meta property="og:description" content="'.escape($desc).'"><meta property="og:url" content="'.escape($canonical).'"><meta property="og:image" content="'.escape($imageUrl).'"><meta property="og:image:secure_url" content="'.escape($imageUrl).'"><meta property="og:image:alt" content="'.escape($imageAlt).'"><link rel="image_src" href="'.escape($imageUrl).'">'.($imageType!==''?'<meta property="og:image:type" content="'.$imageType.'">':'').($imageSize?'<meta property="og:image:width" content="'.$imageSize[0].'"><meta property="og:image:height" content="'.$imageSize[1].'">':'').'<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="'.escape($title).'"><meta name="twitter:description" content="'.escape($desc).'"><meta name="twitter:image" content="'.escape($imageUrl).'"><meta name="twitter:image:alt" content="'.escape($imageAlt).'">';
if($productPage&&$productData&&$productData['price_cents']!==null)$meta.='<meta property="product:price:amount" content="'.number_format($productData['price_cents']/100,2,'.','').'"><meta property="product:price:currency" content="RON"><meta property="product:availability" content="'.($productData['stock_status']==='instock'&&(!$productData['manage_stock']||$productData['stock']>0)?'in stock':'out of stock').'">';
foreach($structured as $item)$meta.='<script type="application/ld+json">'.json_encode($item,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE).'</script>';
$html=file_get_contents(__DIR__.'/dist/index.html');$html=preg_replace('~<title>.*?</title>~s','<title>'.escape($title).'</title>',$html);$html=str_replace('<!--SEO-->',$meta,$html);if($snapshot)$html=str_replace('<div id="root"></div>','<div id="root"><div class="seo-snapshot" hidden aria-hidden="true">'.$snapshot.'</div></div>',$html);echo $html;
