ALTER TABLE categories ADD COLUMN visible BIGINT NOT NULL DEFAULT 1;
ALTER TABLE reviews ADD COLUMN reply TEXT NOT NULL DEFAULT ('');
ALTER TABLE reviews ADD COLUMN replied_at DATETIME;
ALTER TABLE outbox ADD COLUMN status VARCHAR(255) NOT NULL DEFAULT 'pending';
ALTER TABLE outbox ADD COLUMN error TEXT NOT NULL DEFAULT ('');
