ALTER TABLE addresses ADD COLUMN identity_type VARCHAR(10) NOT NULL DEFAULT 'pf';
ALTER TABLE addresses ADD COLUMN company_name VARCHAR(180) NOT NULL DEFAULT '';
ALTER TABLE addresses ADD COLUMN cui VARCHAR(40) NOT NULL DEFAULT '';
ALTER TABLE addresses ADD COLUMN registration_number VARCHAR(80) NOT NULL DEFAULT '';
