ALTER TABLE categories ADD COLUMN visible INTEGER NOT NULL DEFAULT 1;
ALTER TABLE reviews ADD COLUMN reply TEXT NOT NULL DEFAULT '';
ALTER TABLE reviews ADD COLUMN replied_at TEXT;
ALTER TABLE outbox ADD COLUMN status TEXT NOT NULL DEFAULT 'pending';
ALTER TABLE outbox ADD COLUMN error TEXT NOT NULL DEFAULT '';
