<?php
declare(strict_types=1);
require_once __DIR__.'/bootstrap.php';
require_once __DIR__.'/google.php';
require_once __DIR__.'/stripe.php';
require_once __DIR__.'/email.php';
require_once __DIR__.'/tracking.php';
require_once __DIR__.'/recommendations.php';
header('Cache-Control: no-store');
$method=$_SERVER['REQUEST_METHOD'];$route=substr(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),4);
$rawBody=file_get_contents('php://input');$input=json_decode($rawBody,true)??[];
if($route==='/payments/stripe/webhook'&&$method==='POST')stripeWebhook($rawBody,$_SERVER['HTTP_STRIPE_SIGNATURE']??'');
try {
 $cookieName=env('SESSION_COOKIE','floralis_session');$raw=$_COOKIE[$cookieName]??'';$key=hash('sha256',$raw);$session=$raw?one('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?',[$key,(int)(microtime(true)*1000)]):null;
 if(!$session){$raw=bin2hex(random_bytes(32));$key=hash('sha256',$raw);$session=['token_hash'=>$key,'user_id'=>null,'csrf'=>bin2hex(random_bytes(24)),'expires_at'=>(int)(microtime(true)*1000)+604800000];sql('INSERT INTO sessions VALUES(?,?,?,?)',[$key,null,$session['csrf'],$session['expires_at']]);setcookie(env('SESSION_COOKIE','floralis_session'),$raw,['expires'=>time()+604800,'path'=>'/','httponly'=>true,'samesite'=>'Lax','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off']);}
 $user=$session['user_id']?one('SELECT * FROM users WHERE id=? AND active=1',[$session['user_id']]):null;
 if($method==='GET'&&in_array($route,['/auth/google/start','/auth/google/callback']))googleRoute($route,$key);
 if($method!=='GET'){
  $origin=$_SERVER['HTTP_ORIGIN']??'';$host=$_SERVER['HTTP_HOST']??'';if($origin&&parse_url($origin,PHP_URL_HOST).(parse_url($origin,PHP_URL_PORT)?':'.parse_url($origin,PHP_URL_PORT):'')!==$host)abortApi('Origine nepermisă.',403);
  if(!hash_equals($session['csrf'],$_SERVER['HTTP_X_CSRF_TOKEN']??''))abortApi('Sesiunea formularului a expirat. Reîncarcă pagina.',403);
 }
 if(str_starts_with($route,'/admin/')&&($user['role']??'')!=='admin')abortApi('Acces rezervat administratorului.',$user?403:401);
 if(str_starts_with($route,'/account')&&!$user)abortApi('Autentificarea este necesară.',401);
 if($method==='POST'&&preg_match('~^/(auth|contact|newsletter)~',$route)){
  $dir=env('RATE_LIMIT_PATH',ROOT.'/data/rate-limits');if(!is_dir($dir))mkdir($dir,0700,true);$file=$dir.'/'.hash('sha256',($_SERVER['REMOTE_ADDR']??'local').explode('/',$route)[1]).'.json';$f=fopen($file,'c+');flock($f,LOCK_EX);$rate=json_decode(stream_get_contents($f),true)??['start'=>time(),'count'=>0];if(time()-$rate['start']>900)$rate=['start'=>time(),'count'=>0];$rate['count']++;ftruncate($f,0);rewind($f);fwrite($f,j($rate));flock($f,LOCK_UN);fclose($f);if($rate['count']>100)abortApi('Prea multe încercări. Revino peste câteva minute.',429);
 }
 function favoriteIds(?array $u): array {return $u?array_column(all('SELECT product_id FROM favorites WHERE user_id=?',[$u['id']]),'product_id'):[];}
 function cartItems(string $key): array {return array_map('product',all('SELECT p.*,ci.quantity FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.session_hash=?'.(driver()==='mysql'&&db()->inTransaction()?' FOR UPDATE':''),[$key]));}
 function addressInput(array $a): array {
  $r=[];foreach(['name'=>[2,100],'phone'=>[7,20],'street'=>[5,250],'city'=>[2,100],'county'=>[2,100],'postal_code'=>[0,12]] as $k=>$range)$r[$k]=text($a,$k,...$range);
  if(!preg_match('/^[+\d\s()-]{7,20}$/',$r['phone']))abortApi('Telefon invalid.');
  $r['identity_type']=enumValue($a['identity_type']??'pf',['pf','pj']);
  $r['company_name']=text($a,'company_name',$r['identity_type']==='pj'?2:0,180);
  $r['cui']=text($a,'cui',$r['identity_type']==='pj'?2:0,40);
  $r['registration_number']=text($a,'registration_number',0,80);
  if($r['identity_type']==='pj'&&!preg_match('/^[A-Za-z0-9 .\/-]{2,40}$/',$r['cui']))abortApi('CUI / CIF invalid.');
  return $r;
 }
 function quote(string $key,array $a): array {
  $items=cartItems($key);if(!$items)abortApi('Coșul este gol.');$subtotal=0;
  foreach($items as $p){if($p['status']!=='publish'||$p['price_cents']===null||$p['stock_status']!=='instock'||($p['manage_stock']&&$p['quantity']>$p['stock']))abortApi('Produs indisponibil: '.$p['name']);$subtotal+=$p['price_cents']*$p['quantity'];}
  $discount=0;$coupon=null;$code=strtoupper(text($a,'coupon',0,50));
  if($code){$coupon=one('SELECT * FROM discounts WHERE code=? AND active=1',[$code]);if(!$coupon||($coupon['expires_at']&&strtotime($coupon['expires_at'])<time())||($coupon['max_uses']!==null&&$coupon['uses']>=$coupon['max_uses']))abortApi('Cupon invalid sau expirat.');if($subtotal<$coupon['min_cents'])abortApi('Valoarea coșului este sub pragul cuponului.');$discount=min($subtotal,$coupon['type']==='percent'?(int)round($subtotal*$coupon['value']/100):$coupon['value']);}
  $ship=one('SELECT * FROM shipping_methods WHERE id=? AND enabled=1',[(int)($a['shipping_id']??0)]);if(!$ship)abortApi('Alege o metodă de livrare disponibilă.');
  if($ship['zones']&&!empty($a['address']['county'])&&!in_array(strtolower($a['address']['county']),array_map(fn($x)=>strtolower(trim($x)),explode(',',$ship['zones']))))abortApi('Livrarea nu este disponibilă în județul ales.');
  $cost=$ship['free_threshold_cents']!==null&&$subtotal-$discount>=$ship['free_threshold_cents']?0:$ship['price_cents'];return ['items'=>$items,'subtotal_cents'=>$subtotal,'discount_cents'=>$discount,'shipping_cents'=>$cost,'total_cents'=>$subtotal-$discount+$cost,'shipping'=>$ship,'coupon'=>$coupon];
 }
 function orderDetails(array $o): array {$o['address']=decoded($o['shipping_address']);$o['items']=all('SELECT * FROM order_items WHERE order_id=?',[$o['id']]);$o['history']=all('SELECT * FROM order_status_history WHERE order_id=? ORDER BY id',[$o['id']]);return $o;}
 function seoInput(array $a): array {$r=['title'=>text($a,'title',0,200),'description'=>text($a,'description',0,500),'canonical'=>text($a,'canonical',0,500),'og_image'=>text($a,'og_image',0,500),'noindex'=>(bool)($a['noindex']??false),'auto'=>(bool)($a['auto']??false)];if($r['canonical']&&!preg_match('~^https?://~',$r['canonical']))abortApi('Canonical invalid.');return $r;}
 function searchNormalize(string $value): string {
  $value=strtr($value,['Ă'=>'A','Â'=>'A','Î'=>'I','Ș'=>'S','Ş'=>'S','Ț'=>'T','Ţ'=>'T','ă'=>'a','â'=>'a','î'=>'i','ș'=>'s','ş'=>'s','ț'=>'t','ţ'=>'t']);
  $value=strtolower($value);return trim((string)preg_replace('/[^a-z0-9]+/',' ',$value));
 }
 function searchStem(string $word): string {
  if(strlen($word)<4)return $word;
  foreach(['urilor','iilor','elor','ilor','ului','ate','ite','ele','ile','uri','ii','ul','ea','ie','e','i','a'] as $suffix){$length=strlen($suffix);if(str_ends_with($word,$suffix)&&strlen($word)-$length>=3)return substr($word,0,-$length);}
  return $word;
 }
 function smartSearchMatch(string $value,string $query): bool {
  $needle=searchNormalize($query);if($needle==='')return true;$haystack=searchNormalize($value);if(str_contains($haystack,$needle))return true;
  $words=array_values(array_filter(explode(' ',$haystack)));$terms=array_values(array_filter(explode(' ',$needle)));
  foreach($terms as $term){$stem=searchStem($term);$matched=false;foreach($words as $word){$wordStem=searchStem($word);if(str_contains($word,$term)||(strlen($word)>=3&&str_contains($term,$word))||$wordStem===$stem||str_contains($wordStem,$stem)||(strlen($wordStem)>=3&&str_contains($stem,$wordStem))){$matched=true;break;}$limit=max(strlen($term),strlen($word))>=7?2:1;if(levenshtein($term,$word)<=$limit||levenshtein($stem,$wordStem)<=$limit){$matched=true;break;}}if(!$matched)return false;}
  return true;
 }
 function searchExcerpt(string $value,int $length=145): string {
  $value=trim((string)preg_replace('/\s+/u',' ',strip_tags($value)));if(strlen($value)<=$length)return $value;$result='';
  foreach(preg_split('/\s+/u',$value)?:[] as $word){if(strlen($result)+strlen($word)+1>$length)break;$result.=($result===''?'':' ').$word;}
  return ($result!==''?$result:'Informații Floralis').'…';
 }
 function listProducts(bool $admin=false): array {
  $q=$_GET;$where=[$admin?'1=1':"p.status='publish'"];$params=[];$search=substr(trim((string)($q['q']??'')),0,200);
  if(!empty($q['category'])){$where[]='EXISTS(SELECT 1 FROM product_categories pc JOIN categories c ON c.id=pc.category_id WHERE pc.product_id=p.id AND c.slug=?)';$params[]=$q['category'];}
  if($admin&&!empty($q['status'])){$where[]='p.status=?';$params[]=$q['status'];}
  if(($q['stock']??'')==='low'){$where[]='p.manage_stock=1 AND p.stock<=?';$params[]=settingAll()['low_stock_threshold']??5;}
  if(($q['stock']??'')==='out')$where[]="(p.stock_status='outofstock' OR (p.manage_stock=1 AND p.stock=0))";
  foreach(['min'=>'>=','max'=>'<='] as $field=>$op)if(isset($q[$field])&&$q[$field]!==''){$where[]='p.price_cents'.$op.'?';$params[]=max(0,(int)round((float)$q[$field]*100));}
  if(isset($q['ids'])){$ids=array_slice(array_values(array_filter(array_map('intval',explode(',',$q['ids'])),fn($id)=>$id>0)),0,100);if(!$ids)return ['items'=>[],'total'=>0,'page'=>1,'pages'=>0];$where[]='p.id IN ('.implode(',',array_fill(0,count($ids),'?')).')';$params=array_merge($params,$ids);}
  $sort=['price_asc'=>'p.price_cents ASC','price_desc'=>'p.price_cents DESC','name'=>'p.name COLLATE NOCASE ASC','newest'=>'p.id DESC','recommended'=>'p.featured DESC,p.id ASC'][$q['sort']??'']??'p.featured DESC,p.id ASC';$page=max(1,(int)($q['page']??1));$limit=min(100,max(1,(int)($q['limit']??12)));$where=implode(' AND ',$where);
  if($search!==''){$items=all('SELECT p.* FROM products p WHERE '.$where.' ORDER BY '.$sort,$params);$items=array_values(array_filter($items,fn($p)=>smartSearchMatch(implode(' ',[$p['name'],$p['slug'],$p['sku']??'',$p['short_description']??'',$p['description']??'']),$search)));$total=count($items);$items=array_slice($items,($page-1)*$limit,$limit);}
  else{$total=(int)one('SELECT COUNT(*) n FROM products p WHERE '.$where,$params)['n'];$items=all('SELECT p.* FROM products p WHERE '.$where.' ORDER BY '.$sort.' LIMIT '.(int)$limit.' OFFSET '.(int)(($page-1)*$limit),$params);}
  return ['items'=>array_map('product',$items),'total'=>$total,'page'=>$page,'pages'=>(int)ceil($total/$limit)];
 }
 if($route==='/bootstrap'&&$method==='GET')respond(['csrf'=>$session['csrf'],'user'=>safeUser($user),'google'=>googleStatus(),'stripe'=>['configured'=>stripeConfigured(),'mode'=>stripeMode()],'settings'=>settingAll(),'has_posts'=>(int)one("SELECT COUNT(*) n FROM pages WHERE type='post' AND status='publish'")['n']>0,'categories'=>categories(),'admin_categories'=>($user['role']??'')==='admin'?categories(true):[],'favorites'=>favoriteIds($user),'shipping'=>all('SELECT * FROM shipping_methods WHERE enabled=1'),'delivery_time_slots'=>deliveryTimeSlots(),'payments'=>paymentMethods(),'reviews'=>all('SELECT name,rating,body,reply,replied_at FROM reviews WHERE approved=1 ORDER BY id DESC LIMIT 12')]);
 if($route==='/categories')respond(categories());
 if($route==='/products'&&$method==='GET')respond(listProducts());
 if(preg_match('~^/products/([^/]+)$~',$route,$m)){$p=one("SELECT * FROM products WHERE slug=? AND status='publish'",[$m[1]]);if(!$p)abortApi('Produsul nu a fost găsit.',404);$p=product($p);if(!empty($_GET['related']))$p['related_products']=relatedProducts($p,4);respond($p);}
 if($route==='/search'&&$method==='GET'){
  $query=substr(trim((string)($_GET['q']??'')),0,120);if(strlen(searchNormalize($query))<2)respond(['items'=>[],'query'=>$query]);$items=[];$seen=[];
  $add=function(array $item)use(&$items,&$seen){if(isset($seen[$item['url']]))return false;$seen[$item['url']]=true;$items[]=$item;return true;};
  $matched=0;foreach(all("SELECT * FROM products WHERE status='publish' ORDER BY featured DESC,id DESC") as $row)if($matched<6&&smartSearchMatch(implode(' ',[$row['name'],$row['slug'],$row['sku']??'',$row['short_description']??'',$row['description']??'']),$query)){$p=product($row);if($add(['type'=>'Produs','title'=>$p['name'],'url'=>'/produs/'.$p['slug'],'image'=>$p['images'][0]['url']??'','excerpt'=>searchExcerpt($p['short_description']?:$p['description']),'price_cents'=>$p['price_cents']]))$matched++;}
  $matched=0;foreach(all("SELECT * FROM pages WHERE status='publish' ORDER BY type='post' DESC,id DESC") as $page)if($matched<4&&smartSearchMatch(implode(' ',[$page['title'],$page['slug'],$page['body']]),$query)){if($add(['type'=>$page['type']==='post'?'Articol':'Pagină','title'=>$page['title'],'url'=>'/'.$page['slug'],'image'=>$page['image']??'','excerpt'=>searchExcerpt($page['body']),'price_cents'=>null]))$matched++;}
  $matched=0;foreach(categories() as $category)if($matched<3&&smartSearchMatch(implode(' ',[$category['name'],$category['slug'],$category['description']??'']),$query)){if($add(['type'=>'Colecție','title'=>$category['name'],'url'=>'/categorie/'.$category['slug'],'image'=>$category['image']??'','excerpt'=>searchExcerpt($category['description']??'Descoperă colecția Floralis.'),'price_cents'=>null]))$matched++;}
  $static=[['Acasă Floralis','/','flori buchete atelier magazin'],['Magazin','/magazin','toate produsele buchete aranjamente flori'],['Despre noi','/despre-noi','poveste atelier echipa floralis'],['Decoruri florale','/decor-floral','evenimente nunta botez decor oferta'],['Galerie','/galerie','imagini fotografii creatii portofoliu'],['Contact','/contact','telefon email adresa maps tunari mesaj'],['Livrare și transport','/transport-si-livrare','livrare curier transport ridicare'],['Plată securizată','/modalitati-de-plata','plata card ramburs securitate'],['Retur','/retur','retur anulare rambursare'],['Întrebări frecvente','/faq','ajutor intrebari raspunsuri'],['Termeni și condiții','/termeni-si-conditii','legal termeni conditii'],['Confidențialitate și GDPR','/confidentialitate','date personale confidentialitate gdpr cookies']];
  foreach($static as [$title,$url,$keywords])if(smartSearchMatch($title.' '.$keywords,$query))$add(['type'=>'Pagină','title'=>$title,'url'=>$url,'image'=>'','excerpt'=>'Informații utile din universul Floralis.','price_cents'=>null]);
  respond(['items'=>array_slice($items,0,12),'query'=>$query]);
 }
 if($route==='/pages'&&$method==='GET')respond(array_map('contentPage',all("SELECT * FROM pages WHERE status='publish'")));
 if(preg_match('~^/pages/([^/]+)$~',$route,$m)){$p=one("SELECT * FROM pages WHERE slug=? AND status='publish'",[$m[1]]);if(!$p)abortApi('Pagina nu a fost găsită.',404);respond(contentPage($p));}
 if($route==='/cart'&&$method==='GET')respond(['items'=>cartItems($key)]);
 if(preg_match('~^/cart/(\d+)$~',$route,$m)&&$method==='PUT'){$qty=integer($input['quantity']??null,0,99);$p=one("SELECT * FROM products WHERE id=? AND status='publish'",[$m[1]]);if(!$p)abortApi('Produs indisponibil.',404);if($qty&&($p['stock_status']!=='instock'||$p['price_cents']===null||($p['manage_stock']&&$qty>$p['stock'])))abortApi('Cantitatea cerută nu este disponibilă.');if(!$qty)sql('DELETE FROM cart_items WHERE session_hash=? AND product_id=?',[$key,$p['id']]);else sql('INSERT INTO cart_items VALUES(?,?,?) ON CONFLICT(session_hash,product_id) DO UPDATE SET quantity=excluded.quantity',[$key,$p['id'],$qty]);respond(['items'=>cartItems($key)]);}
 if($route==='/checkout/quote'&&$method==='POST')respond(quote($key,$input));
 if($route==='/orders'&&$method==='POST'){
  $address=addressInput($input['address']??[]);$mail=email($input);if(($input['consent']??false)!==true)abortApi('Acceptă termenii pentru a continua.');$idem=text($input,'idempotency_key',36,36);if(!preg_match('/^[a-f0-9-]{36}$/i',$idem))abortApi('Identificator comandă invalid.');$payment=enumValue($input['payment_method']??'', ['cod','card']);$deliveryTimeSlot=text($input,'delivery_time_slot',1,40);if(!in_array($deliveryTimeSlot,deliveryTimeSlots(),true))abortApi('Alege un interval orar de livrare disponibil.',422);$notes=text($input,'notes',0,2000);$couponCode=strtoupper(text($input,'coupon',0,50));if(!array_key_exists('expected_total_cents',$input)||!array_key_exists('expected_discount_cents',$input))abortApi('Reîncarcă pagina de checkout pentru recalcularea sigură a totalului.',409);$expectedTotal=integer($input['expected_total_cents']);$expectedDiscount=integer($input['expected_discount_cents']);
  $o=tx(function()use($key,$input,$address,$mail,$idem,$payment,$deliveryTimeSlot,$notes,$couponCode,$expectedTotal,$expectedDiscount,$user){$old=one('SELECT * FROM orders WHERE session_hash=? AND idempotency_key=?',[$key,$idem]);if($old){if($old['payment_method']!==$payment||$old['delivery_time_slot']!==$deliveryTimeSlot||strtoupper((string)$old['coupon'])!==$couponCode||($expectedTotal!==null&&(int)$old['total_cents']!==$expectedTotal)||($expectedDiscount!==null&&(int)$old['discount_cents']!==$expectedDiscount))abortApi('Totalul sau detaliile comenzii s-au schimbat. Apasă din nou „Plasează comanda”.',409);$old['_new']=false;return $old;}$pay=one('SELECT * FROM payment_methods WHERE code=? AND enabled=1',[$payment]);if(!$pay||($payment==='card'&&!stripeConfigured()))abortApi('Metoda de plată nu este disponibilă.');$q=quote($key,$input);if(($expectedTotal!==null&&$q['total_cents']!==$expectedTotal)||($expectedDiscount!==null&&$q['discount_cents']!==$expectedDiscount))abortApi('Totalul comenzii s-a modificat. Verifică sumarul și încearcă din nou.',409);
   sql('INSERT INTO customers(user_id,email,name,phone,address) VALUES(?,?,?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,phone=excluded.phone,address=excluded.address',[$user['id']??null,$mail,$address['name'],$address['phone'],j($address)]);$c=one('SELECT id FROM customers WHERE email=?',[$mail]);
   sql('INSERT INTO orders(customer_id,user_id,session_hash,idempotency_key,payment_method,shipping_method,delivery_time_slot,shipping_address,subtotal_cents,discount_cents,shipping_cents,total_cents,coupon,notes,access_token) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$c['id'],$user['id']??null,$key,$idem,$payment,$q['shipping']['name'],$deliveryTimeSlot,j($address),$q['subtotal_cents'],$q['discount_cents'],$q['shipping_cents'],$q['total_cents'],$q['coupon']['code']??'',$notes,bin2hex(random_bytes(24))]);$id=(int)db()->lastInsertId();$number='FL-'.str_pad((string)$id,6,'0',STR_PAD_LEFT);sql('UPDATE orders SET number=? WHERE id=?',[$number,$id]);
   foreach($q['items'] as $p){sql('INSERT INTO order_items(order_id,product_id,sku,name,image,quantity,price_cents,total_cents) VALUES(?,?,?,?,?,?,?,?)',[$id,$p['id'],$p['sku'],$p['name'],$p['images'][0]['url']??'',$p['quantity'],$p['price_cents'],$p['price_cents']*$p['quantity']]);if($p['manage_stock']){sql("UPDATE products SET stock=stock-?,stock_status=CASE WHEN stock-?=0 THEN 'outofstock' ELSE stock_status END WHERE id=?",[$p['quantity'],$p['quantity'],$p['id']]);sql('INSERT INTO stock_movements(product_id,delta,balance,reason) VALUES(?,?,?,?)',[$p['id'],-$p['quantity'],$p['stock']-$p['quantity'],$number]);}}
   if($q['coupon'])sql('UPDATE discounts SET uses=uses+1 WHERE id=?',[$q['coupon']['id']]);sql("INSERT INTO order_status_history(order_id,status,note) VALUES(?,'received','Comandă primită')",[$id]);if($payment==='cod')sql('DELETE FROM cart_items WHERE session_hash=?',[$key]);$saved=one('SELECT * FROM orders WHERE id=?',[$id]);$saved['_new']=true;return $saved;});
  $isNew=$o['_new']??false;if($payment==='card'){try{$o=stripeCheckout($o);}catch(Throwable $e){tx(fn()=>stripeDiscardUnpaidOrder($o));throw $e;}}
  if($isNew&&$payment==='cod')sendOrderConfirmationEmails($o);
  foreach(all('SELECT product_id FROM order_items WHERE order_id=?',[$o['id']]) as $i)stripeQueue('product',(int)$i['product_id']);
  $trackingUrl=rtrim(env('APP_URL','http://localhost:5173'),'/').'/api/orders/'.rawurlencode((string)$o['number']).'/tracking?token='.rawurlencode((string)$o['access_token']);respond(['number'=>$o['number'],'token'=>$o['access_token'],'id'=>$o['id'],'total_cents'=>$o['total_cents'],'checkout_url'=>$o['stripe_checkout_url'],'tracking_url'=>$trackingUrl],201);
 }
 if(preg_match('~^/orders/([^/]+)/tracking$~',$route,$m)&&$method==='GET'){$o=one('SELECT * FROM orders WHERE number=?',[$m[1]]);if(!$o||((!hash_equals((string)$o['access_token'],(string)($_GET['token']??'')))&&!($user&&$o['user_id']===$user['id'])&&($user['role']??'')!=='admin'))abortApi('Comanda nu a fost găsită.',404);$view='';$snapshot=orderEmailRecord($o);$snapshot['history']=all('SELECT * FROM order_status_history WHERE order_id=? ORDER BY id',[$o['id']]);if(($_GET['payment']??'')==='cancelled'&&$o['payment_method']==='card'&&$o['payment_status']==='unpaid'){$ids=array_column($snapshot['items'],'product_id');if($o['stripe_session_id']&&stripeConfigured())try{stripeRequest('POST','/checkout/sessions/'.$o['stripe_session_id'].'/expire');}catch(Throwable $ignored){}tx(fn()=>stripeDiscardUnpaidOrder($o));foreach($ids as $id)stripeQueue('product',(int)$id);$o=$snapshot;$view='payment_cancelled';}else{$fresh=stripeReconcile($o);if(!$fresh){$o=$snapshot;$view='payment_cancelled';}else{$o=orderEmailRecord($fresh);$o['history']=all('SELECT * FROM order_status_history WHERE order_id=? ORDER BY id',[$fresh['id']]);}}header("Content-Security-Policy: default-src 'self'; img-src 'self' https: data:; style-src 'unsafe-inline'; script-src 'unsafe-inline' https://www.googletagmanager.com; connect-src 'self' https://www.google-analytics.com https://region1.google-analytics.com https://www.googletagmanager.com; frame-src https://www.googletagmanager.com; base-uri 'none'; frame-ancestors 'none'");header('X-Robots-Tag: noindex, nofollow');header('Content-Type: text/html; charset=utf-8');echo orderTrackingHtml($o,$view);exit;}
 if(preg_match('~^/orders/([^/]+)$~',$route,$m)&&$method==='GET'){$o=one('SELECT * FROM orders WHERE number=?',[$m[1]]);if(!$o||(($o['access_token']!==($_GET['token']??''))&&!($user&&$o['user_id']===$user['id'])&&($user['role']??'')!=='admin'))abortApi('Comanda nu a fost găsită.',404);$o=stripeReconcile($o);if(!$o)abortApi('Comanda neplătită nu mai este activă.',404);respond(orderDetails($o));}
 function loginUser(array $u,string $old): never {$raw=bin2hex(random_bytes(32));$hash=hash('sha256',$raw);$csrf=bin2hex(random_bytes(24));tx(function()use($u,$old,$hash,$csrf){sql('INSERT INTO sessions VALUES(?,?,?,?)',[$hash,$u['id'],$csrf,(int)(microtime(true)*1000)+604800000]);sql('UPDATE cart_items SET session_hash=? WHERE session_hash=?',[$hash,$old]);sql('DELETE FROM sessions WHERE token_hash=?',[$old]);});setcookie(env('SESSION_COOKIE','floralis_session'),$raw,['expires'=>time()+604800,'path'=>'/','httponly'=>true,'samesite'=>'Lax','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off']);respond(['user'=>safeUser($u),'csrf'=>$csrf]);}
 if($route==='/auth/register'&&$method==='POST'){$mail=email($input);$name=text($input,'name',2,100);$pass=text($input,'password',10,128);if(one('SELECT id FROM users WHERE email=?',[$mail]))abortApi('Există deja un cont cu această adresă.');sql('INSERT INTO users(email,password_hash,name) VALUES(?,?,?)',[$mail,password_hash($pass,PASSWORD_DEFAULT),$name]);$u=one('SELECT * FROM users WHERE id=?',[(int)db()->lastInsertId()]);loginUser($u,$key);}
 if($route==='/auth/login'&&$method==='POST'){$mail=email($input);$pass=text($input,'password',1,128);$u=one('SELECT * FROM users WHERE email=? AND active=1',[$mail]);if(!$u||!password_verify($pass,$u['password_hash']))abortApi('Email sau parolă incorectă.',401);if(!empty($input['admin'])&&$u['role']!=='admin')abortApi('Cont fără acces admin.',403);loginUser($u,$key);}
 if($route==='/auth/logout'&&$method==='POST'){sql('UPDATE sessions SET user_id=NULL,csrf=? WHERE token_hash=?',[bin2hex(random_bytes(24)),$key]);respond(['ok'=>true]);}
 if($route==='/auth/forgot'&&$method==='POST'){$mail=email($input);$u=one('SELECT * FROM users WHERE email=? AND active=1',[$mail]);if($u){$token=bin2hex(random_bytes(32));sql('DELETE FROM password_resets WHERE user_id=?',[$u['id']]);sql('INSERT INTO password_resets VALUES(?,?,?)',[hash('sha256',$token),$u['id'],(int)(microtime(true)*1000)+3600000]);$resetUrl=rtrim(env('APP_URL','http://localhost:5173'),'/').'/cont/resetare?token='.$token;queueMail($mail,'Resetare parolă Floralis',"Bună, ".$u['name']."!\n\nAm primit o solicitare de resetare a parolei contului tău Floralis. Linkul este valabil timp de o oră:\n".$resetUrl."\n\nDacă nu ai cerut schimbarea parolei, poți ignora acest mesaj în siguranță.");}respond(['message'=>'Dacă există un cont, instrucțiunile de resetare au fost trimise.']);}
 if($route==='/auth/reset'&&$method==='POST'){$token=text($input,'token',20,100);$pass=text($input,'password',10,128);$r=one('SELECT * FROM password_resets WHERE token_hash=? AND expires_at>?',[hash('sha256',$token),(int)(microtime(true)*1000)]);if(!$r)abortApi('Link invalid sau expirat.');tx(function()use($r,$pass){sql('UPDATE users SET password_hash=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$r['user_id']]);sql('DELETE FROM password_resets WHERE user_id=?',[$r['user_id']]);sql('DELETE FROM sessions WHERE user_id=?',[$r['user_id']]);});respond(['ok'=>true]);}
 if($route==='/account'&&$method==='GET')respond(['user'=>safeUser($user),'addresses'=>all('SELECT * FROM addresses WHERE user_id=?',[$user['id']]),'orders'=>all("SELECT * FROM orders WHERE user_id=? AND (payment_method!='card' OR payment_status='paid') ORDER BY id DESC",[$user['id']]),'favorites'=>favoriteIds($user)]);
 if($route==='/account/profile'&&$method==='PATCH'){
  $name=text($input,'name',2,100);$phone=text($input,'phone',0,20);$mail=array_key_exists('email',$input)?email($input):$user['email'];
  if($phone!==''&&!preg_match('/^[+\d\s()-]{7,20}$/',$phone))abortApi('Telefon invalid.');
  tx(function()use($name,$phone,$mail,$user){
   if(one('SELECT id FROM users WHERE email=? AND id<>?',[$mail,$user['id']]))abortApi('Există deja un cont cu această adresă de email.',409);
   $customer=one('SELECT id FROM customers WHERE user_id=?',[$user['id']]);
   if($customer&&one('SELECT id FROM customers WHERE email=? AND id<>?',[$mail,$customer['id']]))abortApi('Adresa de email este deja asociată unui alt client.',409);
   sql('UPDATE users SET name=?,phone=?,email=? WHERE id=?',[$name,$phone,$mail,$user['id']]);
   if($customer)sql('UPDATE customers SET name=?,phone=?,email=? WHERE id=?',[$name,$phone,$mail,$customer['id']]);
  });
  respond(['ok'=>true,'user'=>safeUser(one('SELECT * FROM users WHERE id=?',[$user['id']]))]);
 }
 if($route==='/account/addresses'&&$method==='POST'){$a=addressInput($input);sql('INSERT INTO addresses(user_id,name,phone,street,city,county,postal_code,identity_type,company_name,cui,registration_number) VALUES(?,?,?,?,?,?,?,?,?,?,?)',array_merge([$user['id']],array_values($a)));respond(['ok'=>true]);}
 if(preg_match('~^/account/addresses/(\d+)$~',$route,$m)&&$method==='DELETE'){sql('DELETE FROM addresses WHERE id=? AND user_id=?',[$m[1],$user['id']]);respond(['ok'=>true]);}
 if($route==='/account/favorites'&&$method==='PUT'){$ids=$input['ids']??[];if(!is_array($ids)||count($ids)>100)abortApi('Favorite invalide.');tx(function()use($ids,$user){sql('DELETE FROM favorites WHERE user_id=?',[$user['id']]);foreach($ids as $id){$id=integer($id,1);if(one('SELECT id FROM products WHERE id=?',[$id]))sql('INSERT OR IGNORE INTO favorites VALUES(?,?)',[$user['id'],$id]);}});respond(['ids'=>favoriteIds($user)]);}
 if($route==='/account/reviews'&&$method==='POST'){sql('INSERT INTO reviews(user_id,product_id,name,rating,body) VALUES(?,?,?,?,?)',[$user['id'],$input['product_id']??null,$user['name'],integer($input['rating']??null,1,5),text($input,'body',10,2000)]);respond(['ok'=>true]);}
 if($route==='/contact'&&$method==='POST'){if(($input['consent']??false)!==true)abortApi('Acceptă politica de confidențialitate.');$name=text($input,'name',2,100);$contactEmail=email($input);$phone=text($input,'phone',0,20);$subject=text($input,'subject',0,200);$body=text($input,'body',10,5000);sql('INSERT INTO messages(name,email,phone,subject,body) VALUES(?,?,?,?,?)',[$name,$contactEmail,$phone,$subject,$body]);$messageId=(int)db()->lastInsertId();$notify=mailConfig(true)['notification_email'];queueMail($notify,'Mesaj nou Floralis · '.($subject?:'Contact website'),"Ai primit un mesaj nou din website.\n\nNume: ".$name."\nEmail client: ".$contactEmail."\nTelefon: ".($phone?:'—')."\nSubiect: ".($subject?:'Mesaj general')."\n\nMesaj:\n".$body."\n\nRăspunde din administrare:\n".rtrim(env('APP_URL','http://localhost:5173'),'/').'/admin/mesaje?mesaj='.$messageId);respond(['ok'=>true],201);}
 if($route==='/newsletter'&&$method==='POST'){if(($input['consent']??false)!==true)abortApi('Acceptă politica de confidențialitate.');sql('INSERT OR IGNORE INTO newsletter(email) VALUES(?)',[email($input)]);respond(['ok'=>true]);}


 if($route==='/admin/stripe'&&$method==='GET')respond(stripeStatus());
 if($route==='/admin/stripe/sync'&&$method==='POST'){if(!stripeConfigured())abortApi('Stripe neconfigurat.',503);$ids=$input['ids']??[];if(!is_array($ids)||count($ids)>5)abortApi('Maximum 5 produse într-un lot.');foreach($ids as $id)stripeQueue('product',integer($id,1));foreach(all('SELECT id FROM shipping_methods') as $ship)stripeQueue('shipping',(int)$ship['id']);respond(stripeStatus());}
 if($route==='/payments/stripe/cancel'&&$method==='POST'){$number=text($input,'number',1,50);$o=one('SELECT * FROM orders WHERE number=?',[$number]);if(!$o||$o['payment_method']!=='card'||(!hash_equals($o['access_token'],text($input,'token',1,100))&&($user['role']??'')!=='admin'))abortApi('Comandă inexistentă.',404);$o=stripeReconcile($o);if(!$o)respond(['ok'=>true]);if($o['payment_status']==='paid')abortApi('Plata a fost confirmată; anularea necesită rambursare.',409);$ids=array_column(all('SELECT product_id FROM order_items WHERE order_id=?',[$o['id']]),'product_id');if($o['stripe_session_id'])stripeRequest('POST','/checkout/sessions/'.$o['stripe_session_id'].'/expire');tx(fn()=>stripeDiscardUnpaidOrder($o));foreach($ids as $id)stripeQueue('product',(int)$id);respond(['ok'=>true]);}
 if(preg_match('~^/admin/orders/(\d+)/stripe/refund$~',$route,$m)&&$method==='POST'){$o=one('SELECT * FROM orders WHERE id=?',[$m[1]]);if(!$o||$o['payment_method']!=='card'||$o['payment_status']!=='paid'||!$o['stripe_payment_intent'])abortApi('Comanda nu are o plată Stripe rambursabilă.',409);$refund=stripeRequest('POST','/refunds',['payment_intent'=>$o['stripe_payment_intent'],'amount'=>$o['total_cents'],'metadata'=>['application'=>'floralis','local_order_id'=>(string)$o['id']]],'floralis-refund-'.$o['id'].'-'.$o['stripe_payment_intent']);if($refund['status']!=='succeeded')abortApi('Rambursarea Stripe este în așteptare.',409);tx(function()use($o,$refund){sql("UPDATE orders SET payment_status='refunded',stripe_refund_id=? WHERE id=?",[$refund['id'],$o['id']]);stripeCancelOrder(one('SELECT * FROM orders WHERE id=?',[$o['id']]),'Rambursare Stripe');});respond(['ok'=>true]);}


 if(preg_match('~^/admin/products/(\d+)/permanent$~',$route,$m)&&$method==='DELETE'){$id=(int)$m[1];$p=one('SELECT * FROM products WHERE id=?',[$id]);if(!$p)abortApi('Produs inexistent.',404);if(one('SELECT id FROM order_items WHERE product_id=?',[$id]))abortApi('Produsul apare în comenzi; folosește arhivarea.',409);sql("UPDATE products SET status='archived' WHERE id=?",[$id]);stripeQueueRequired('product',$id);tx(function()use($id){sql('DELETE FROM stripe_catalog WHERE product_id=?',[$id]);sql("DELETE FROM stripe_sync WHERE entity='product' AND local_id=?",[$id]);sql('DELETE FROM stock_movements WHERE product_id=?',[$id]);sql('DELETE FROM reviews WHERE product_id=?',[$id]);sql('DELETE FROM products WHERE id=?',[$id]);});respond(['ok'=>true]);}
 if($route==='/admin/products/generate-sku'&&$method==='POST'){tx(function(){foreach(all("SELECT id FROM products WHERE sku IS NULL OR sku='' ORDER BY id") as $p){$sku='FL-'.str_pad((string)$p['id'],5,'0',STR_PAD_LEFT);while(one('SELECT id FROM products WHERE sku=?',[$sku]))$sku.='A';sql('UPDATE products SET sku=? WHERE id=?',[$sku,$p['id']]);stripeQueue('product',(int)$p['id'],false);}});respond(['ok'=>true]);}
 if(preg_match('~^/admin/categories/(\d+)/visibility$~',$route,$m)&&$method==='PATCH'){sql('UPDATE categories SET visible=? WHERE id=?',[integer($input['visible']??1,0,1),$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/email/settings'&&$method==='GET')respond(mailConfig());
 if($route==='/admin/email/settings'&&$method==='PUT'){saveMailConfig($input);respond(['ok'=>true]);}
 if($route==='/admin/email/test'&&$method==='POST'){$recipient=email($input);$delivery=queueMail($recipient,'Test SMTP Floralis',"Configurarea SMTP Floralis funcționează corect.\n\nExpeditor: ".mailConfig(true)['from_email']."\nServer: ".mailConfig(true)['host'].':'.mailConfig(true)['port']);if($delivery['status']!=='sent')abortApi($delivery['error']?:'Emailul de test nu a putut fi trimis.',502);respond(['ok'=>true]);}
  if(preg_match('~^/admin/newsletter/(\d+)$~',$route,$m)&&$method==='DELETE'){sql('DELETE FROM newsletter WHERE id=?',[$m[1]]);respond(['ok'=>true]);}

 if($route==='/admin/dashboard'&&$method==='GET'){$days=(int)($_GET['days']??30);if(!in_array($days,[7,30,90,365]))$days=30;$period='-'.$days.' days';$visible="(payment_method!='card' OR payment_status='paid')";$eligible="status NOT IN ('cancelled','returned') AND $visible";$stats=one("SELECT COUNT(*) orders,COALESCE(SUM(total_cents),0) revenue FROM orders WHERE $eligible AND created_at>=datetime('now',?)",[$period]);$stats['customers']=one('SELECT COUNT(*) n FROM customers')['n'];$stats['products']=one("SELECT COUNT(*) n FROM products WHERE status!='archived'")['n'];$stats['low_stock']=one('SELECT COUNT(*) n FROM products WHERE manage_stock=1 AND stock<=?',[settingAll()['low_stock_threshold']??5])['n'];respond(['stats'=>$stats,'series'=>all("SELECT date(created_at) day,SUM(total_cents) revenue FROM orders WHERE $eligible AND created_at>=datetime('now',?) GROUP BY date(created_at) ORDER BY day",[$period]),'statuses'=>all("SELECT status,COUNT(*) count FROM orders WHERE $visible GROUP BY status"),'recent'=>all("SELECT o.*,c.name customer_name,c.email FROM orders o JOIN customers c ON c.id=o.customer_id WHERE (o.payment_method!='card' OR o.payment_status='paid') ORDER BY o.id DESC LIMIT 8"),'top'=>all("SELECT i.name,SUM(i.quantity) quantity,SUM(i.total_cents) total FROM order_items i JOIN orders o ON o.id=i.order_id WHERE o.$eligible AND o.created_at>=datetime('now',?) GROUP BY i.product_id,i.name ORDER BY total DESC LIMIT 5",[$period])]);}
 if($route==='/admin/notifications'&&$method==='GET'){$orders=one("SELECT COUNT(*) n FROM orders WHERE status IN ('received','confirmed') AND (payment_method!='card' OR payment_status='paid')");$messages=one("SELECT COUNT(*) n FROM messages WHERE status='new'");respond(['orders'=>(int)($orders['n']??0),'messages'=>(int)($messages['n']??0)]);}
 if($route==='/admin/products/availability'&&$method==='GET'){$field=(string)($_GET['field']??'');if(!in_array($field,['name','slug','sku'],true))abortApi('Câmp invalid.',422);$value=trim(substr((string)($_GET['value']??''),0,$field==='name'?250:200));if($value==='')respond(['available'=>true]);$exclude=max(0,(int)($_GET['exclude_id']??0));$found=$exclude?one("SELECT id FROM products WHERE lower($field)=lower(?) AND id<>?",[$value,$exclude]):one("SELECT id FROM products WHERE lower($field)=lower(?)",[$value]);respond(['available'=>!$found]);}
 if($route==='/admin/products'&&$method==='GET')respond(listProducts(true));
 if(preg_match('~^/admin/products/(\d+)$~',$route,$m)&&$method==='GET'){$p=one('SELECT * FROM products WHERE id=?',[$m[1]]);if(!$p)abortApi('Produs inexistent.',404);respond(product($p));}
 function saveProduct(array $a,?int $id): array {
  $fields=['sku','name','slug','status','price_cents','regular_price_cents','sale_price_cents','stock','stock_status','manage_stock','featured','description','short_description','tax_status','tax_class'];$p=[];$sku=isset($a['sku'])?text($a,'sku',0,80):'';$p['sku']=$sku===''?null:$sku;$p['name']=text($a,'name',2,250);$p['slug']=text($a,'slug',1,200);if(!preg_match('/^[a-z0-9-]+$/',$p['slug']))abortApi('Slug invalid.');foreach(['name'=>'nume','slug'=>'slug','sku'=>'SKU'] as $field=>$label)if($p[$field]!==null&&$p[$field]!==''&&($id?one("SELECT id FROM products WHERE lower($field)=lower(?) AND id<>?",[$p[$field],$id]):one("SELECT id FROM products WHERE lower($field)=lower(?)",[$p[$field]])))abortApi('Acest '.$label.' este deja folosit.',409);$p['status']=enumValue($a['status']??'publish',['publish','draft','archived']);foreach(['price_cents','regular_price_cents','sale_price_cents','stock'] as $f)$p[$f]=($a[$f]??null)===null?null:integer($a[$f]);$p['stock_status']=enumValue($a['stock_status']??'instock',['instock','outofstock']);$p['manage_stock']=$p['stock']!==null&&$p['stock']>0?1:0;if(!$p['manage_stock']){$p['stock']=null;$p['stock_status']='instock';}$p['featured']=integer($a['featured']??0,0,1);foreach(['description'=>20000,'short_description'=>10000,'tax_status'=>50,'tax_class'=>50] as $f=>$max)$p[$f]=text($a,$f,0,$max);if($p['sale_price_cents']!==null){if($p['regular_price_cents']!==null&&$p['sale_price_cents']>$p['regular_price_cents'])abortApi('Preț redus invalid.');$p['price_cents']=$p['sale_price_cents'];}
  $cats=$a['categories']??[];$imgs=$a['images']??[];if(!is_array($cats)||count($cats)>30||!is_array($imgs)||count($imgs)>30)abortApi('Categorii sau imagini invalide.');foreach($cats as $cat)if(!one('SELECT id FROM categories WHERE id=?',[integer($cat,1)]))abortApi('Categorie invalidă.');foreach($imgs as $img)if(!is_array($img)||!preg_match('~^/(assets/floralis/|uploads/)[a-zA-Z0-9_.\/-]+$~',$img['url']??'')||str_contains($img['url'],'..'))abortApi('Imagine invalidă.');$seo=productSeoDefaults($p,seoInput($a['seo']??[]));
  $saved=tx(function()use($p,$fields,$id,$cats,$imgs,$seo){$vals=array_map(fn($f)=>$p[$f],$fields);$vals[]=j($seo);if($id){$old=one('SELECT * FROM products WHERE id=?',[$id]);if(!$old)abortApi('Produs inexistent.',404);sql('UPDATE products SET '.implode(',',array_map(fn($f)=>$f.'=?',$fields)).',seo=? WHERE id=?',array_merge($vals,[$id]));if($p['manage_stock']&&$p['stock']!==$old['stock'])sql('INSERT INTO stock_movements(product_id,delta,balance,reason) VALUES(?,?,?,?)',[$id,$p['stock']-($old['stock']??0),$p['stock'],'Editare produs']);$pid=$id;}else{sql('INSERT INTO products('.implode(',',$fields).',seo) VALUES('.implode(',',array_fill(0,count($vals),'?')).')',$vals);$pid=(int)db()->lastInsertId();}sql('DELETE FROM product_categories WHERE product_id=?',[$pid]);sql('DELETE FROM product_images WHERE product_id=?',[$pid]);foreach(array_unique($cats) as $cat)sql('INSERT INTO product_categories VALUES(?,?)',[$pid,$cat]);foreach($imgs as $idx=>$img)sql('INSERT INTO product_images(product_id,url,alt,sort_order) VALUES(?,?,?,?)',[$pid,$img['url'],text($img,'alt',0,250),$idx]);return $pid;});stripeQueueRequired('product',$saved);$savedProduct=product(one('SELECT * FROM products WHERE id=?',[$saved]));announceNewsletter('product',$savedProduct);return $savedProduct;
 }
 if(($route==='/admin/products'&&$method==='POST')||(preg_match('~^/admin/products/(\d+)$~',$route,$m)&&$method==='PUT'))respond(saveProduct($input,isset($m[1])?(int)$m[1]:null));
 if(preg_match('~^/admin/products/(\d+)$~',$route,$m)&&$method==='DELETE'){sql("UPDATE products SET status='archived' WHERE id=?",[$m[1]]);stripeQueueRequired('product',(int)$m[1]);respond(['ok'=>true]);}
 if(preg_match('~^/admin/products/(\d+)/duplicate$~',$route,$m)&&$method==='POST'){$p=one('SELECT * FROM products WHERE id=?',[$m[1]]);if(!$p)abortApi('Produs inexistent.',404);$p=product($p);$p['name'].=' — copie';$p['slug'].='-copie-'.bin2hex(random_bytes(3));$p['sku']=null;$p['status']='draft';$p['seo']=[];$p['categories']=array_column($p['categories'],'id');respond(saveProduct($p,null));}
 if($route==='/admin/categories/availability'&&$method==='GET'){$field=(string)($_GET['field']??'');if(!in_array($field,['name','slug'],true))abortApi('Câmp invalid.',422);$value=trim(substr((string)($_GET['value']??''),0,$field==='name'?150:200));if($value==='')respond(['available'=>true]);$exclude=max(0,(int)($_GET['exclude_id']??0));$found=$exclude?one("SELECT id FROM categories WHERE lower($field)=lower(?) AND id<>?",[$value,$exclude]):one("SELECT id FROM categories WHERE lower($field)=lower(?)",[$value]);respond(['available'=>!$found]);}
 if($route==='/admin/categories'&&$method==='GET')respond(categories(true));
 if(($route==='/admin/categories'&&$method==='POST')||(preg_match('~^/admin/categories/(\d+)$~',$route,$m)&&$method==='PUT')){$id=isset($m[1])?(int)$m[1]:null;$parent=($input['parent_id']??null)===null?null:integer($input['parent_id'],1);$cur=$parent;$seen=$id?[$id]:[];while($cur){if(in_array($cur,$seen))abortApi('Ierarhia nu poate conține un ciclu.');$seen[]=$cur;$c=one('SELECT parent_id FROM categories WHERE id=?',[$cur]);if(!$c)abortApi('Categorie părinte inexistentă.');$cur=$c['parent_id'];}$slug=text($input,'slug',1,200);if(!preg_match('/^[a-z0-9-]+$/',$slug))abortApi('Slug invalid.');$name=text($input,'name',2,150);$description=text($input,'description',0,10000);$image=text($input,'image',0,500);$seo=categorySeoDefaults(['name'=>$name,'slug'=>$slug,'description'=>$description,'image'=>$image],seoInput($input['seo']??[]));$v=[$name,$slug,$parent,$description,$image,(int)($input['sort_order']??0),j($seo),integer($input['visible']??1,0,1)];if($id&&!one('SELECT id FROM categories WHERE id=?',[$id]))abortApi('Categorie inexistentă.',404);if($id)sql('UPDATE categories SET name=?,slug=?,parent_id=?,description=?,image=?,sort_order=?,seo=?,visible=? WHERE id=?',array_merge($v,[$id]));else sql('INSERT INTO categories(name,slug,parent_id,description,image,sort_order,seo,visible) VALUES(?,?,?,?,?,?,?,?)',$v);respond(['ok'=>true]);}
 if(preg_match('~^/admin/categories/(\d+)$~',$route,$m)&&$method==='DELETE'){if(one('SELECT id FROM categories WHERE parent_id=?',[$m[1]])||one('SELECT product_id FROM product_categories WHERE category_id=?',[$m[1]]))abortApi('Mută produsele și subcategoriile înainte de ștergere.',409);sql('DELETE FROM categories WHERE id=?',[$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/orders'&&$method==='GET'){$w=["(o.payment_method!='card' OR o.payment_status='paid')"];$v=[];if(!empty($_GET['status'])){$w[]='o.status=?';$v[]=$_GET['status'];}if(!empty($_GET['q'])){$w[]='(o.number LIKE ? OR c.email LIKE ? OR c.name LIKE ?)';$v=array_merge($v,array_fill(0,3,'%'.substr($_GET['q'],0,150).'%'));}respond(all('SELECT o.*,c.name customer_name,c.email FROM orders o JOIN customers c ON c.id=o.customer_id WHERE '.implode(' AND ',$w).' ORDER BY o.id DESC LIMIT 500',$v));}
 if(preg_match('~^/admin/orders/(\d+)$~',$route,$m)&&$method==='GET'){$o=one("SELECT o.*,c.name customer_name,c.email,c.phone FROM orders o JOIN customers c ON c.id=o.customer_id WHERE o.id=? AND (o.payment_method!='card' OR o.payment_status='paid')",[$m[1]]);if(!$o)abortApi('Comandă inexistentă.',404);respond(orderDetails($o));}
 if(preg_match('~^/admin/orders/(\d+)$~',$route,$m)&&$method==='PATCH'){
  $status=enumValue($input['status']??'', ['received','confirmed','processing','prepared','shipped','delivered','cancelled','returned']);
  $paid=enumValue($input['payment_status']??'', ['unpaid','paid','refunded']);
  $notes=text($input,'admin_notes',0,5000);$addr=isset($input['address'])?addressInput($input['address']):null;$notifyCustomer=!empty($input['notify_customer']);$statusChanged=false;$emailDelivery='not_requested';
  tx(function()use($m,$status,$paid,$notes,$addr,$notifyCustomer,&$statusChanged,&$emailDelivery){
   $o=one('SELECT * FROM orders WHERE id=?',[$m[1]]);if(!$o)abortApi('Comandă inexistentă.',404);
   if($o['payment_method']==='card'&&$paid!==$o['payment_status'])abortApi('Plata Stripe se actualizează din confirmarea Stripe sau rambursare.',409);
   if($o['payment_method']==='card'&&$o['stripe_session_id']&&$status==='cancelled'&&$o['payment_status']==='unpaid')abortApi('Anulează întâi sesiunea Stripe din acțiunea dedicată.',409);
   if(in_array($o['status'],['cancelled','returned'])&&$status!==$o['status'])abortApi('Comanda închisă nu poate fi reactivată.',409);
   if($status==='returned'&&!in_array($o['status'],['delivered','returned']))abortApi('Doar comenzile livrate pot fi returnate.');
   if($status==='cancelled'&&$o['status']==='delivered')abortApi('O comandă livrată poate fi returnată, nu anulată.');
   if(in_array($status,['cancelled','returned'])&&!$o['stock_restored']){foreach(all('SELECT * FROM order_items WHERE order_id=?',[$o['id']]) as $i){$p=one('SELECT * FROM products WHERE id=?',[$i['product_id']]);if($p&&$p['manage_stock']){sql("UPDATE products SET stock=stock+?,stock_status='instock' WHERE id=?",[$i['quantity'],$p['id']]);sql('INSERT INTO stock_movements(product_id,delta,balance,reason) VALUES(?,?,?,?)',[$p['id'],$i['quantity'],$p['stock']+$i['quantity'],'Restituire '.$o['number']]);}}sql('UPDATE orders SET stock_restored=1 WHERE id=?',[$o['id']]);}
   sql('UPDATE orders SET status=?,payment_status=?,admin_notes=?,shipping_address=? WHERE id=?',[$status,$paid,$notes,$addr?j($addr):$o['shipping_address'],$o['id']]);
   if($status!==$o['status']){$statusChanged=true;sql('INSERT INTO order_status_history(order_id,status,note) VALUES(?,?,?)',[$o['id'],$status,$notes]);if($notifyCustomer){$delivery=sendOrderStatusUpdateEmail(one('SELECT * FROM orders WHERE id=?',[$o['id']]));$emailDelivery=(string)($delivery['status']??'error');}}
  });
  respond(['ok'=>true,'status_changed'=>$statusChanged,'email_delivery'=>$emailDelivery]);
 }
 if($route==='/admin/customers'&&$method==='GET')respond(array_map(function($c){$c['address']=decoded($c['address']);$c['orders']=all("SELECT number,status,total_cents,created_at FROM orders WHERE customer_id=? AND (payment_method!='card' OR payment_status='paid') ORDER BY id DESC",[$c['id']]);$c['addresses']=$c['user_id']?all('SELECT * FROM addresses WHERE user_id=?',[$c['user_id']]):[];return $c;},all("SELECT c.*,u.active,(SELECT COUNT(*) FROM orders o WHERE o.customer_id=c.id AND (o.payment_method!='card' OR o.payment_status='paid')) order_count,(SELECT COALESCE(SUM(total_cents),0) FROM orders o WHERE o.customer_id=c.id AND status NOT IN ('cancelled','returned') AND (o.payment_method!='card' OR o.payment_status='paid')) total_cents FROM customers c LEFT JOIN users u ON u.id=c.user_id ORDER BY c.id DESC")));
 if($route==='/admin/accounts'&&$method==='GET')respond(all('SELECT id,email,name,phone,role,active,created_at FROM users ORDER BY id DESC'));
 if(preg_match('~^/admin/accounts/(\d+)$~',$route,$m)&&$method==='PATCH'){$active=integer($input['active']??null,0,1);$u=one('SELECT * FROM users WHERE id=?',[$m[1]]);if(!$u||$u['role']==='admin')abortApi('Contul admin nu poate fi dezactivat aici.');sql('UPDATE users SET active=? WHERE id=?',[$active,$m[1]]);if(!$active)sql('DELETE FROM sessions WHERE user_id=?',[$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/stock'&&$method==='GET')respond(['products'=>all("SELECT id,name,sku,stock,stock_status,manage_stock FROM products WHERE status!='archived' ORDER BY manage_stock DESC,stock ASC"),'history'=>all('SELECT m.*,p.name FROM stock_movements m JOIN products p ON p.id=m.product_id ORDER BY m.id DESC LIMIT 100')]);
 if(preg_match('~^/admin/stock/(\d+)$~',$route,$m)&&$method==='POST'){$stock=integer($input['stock']??null);$reason=text($input,'reason',3,200);tx(function()use($stock,$reason,$m){$p=one('SELECT * FROM products WHERE id=?',[$m[1]]);if(!$p)abortApi('Produs inexistent.',404);$managed=$stock>0?1:0;$saved=$managed?$stock:null;sql("UPDATE products SET stock=?,manage_stock=?,stock_status='instock' WHERE id=?",[$saved,$managed,$p['id']]);sql('INSERT INTO stock_movements(product_id,delta,balance,reason) VALUES(?,?,?,?)',[$p['id'],$stock-($p['stock']??0),$saved,$reason]);});stripeQueue('product',(int)$m[1]);respond(['ok'=>true]);}
 if($route==='/admin/discounts/availability'&&$method==='GET'){$code=strtoupper(trim(substr((string)($_GET['code']??''),0,50)));if($code==='')respond(['available'=>true]);$exclude=max(0,(int)($_GET['exclude_id']??0));$found=$exclude?one('SELECT id FROM discounts WHERE upper(code)=upper(?) AND id<>?',[$code,$exclude]):one('SELECT id FROM discounts WHERE upper(code)=upper(?)',[$code]);respond(['available'=>!$found]);}
 if($route==='/admin/discounts'&&$method==='GET')respond(all('SELECT * FROM discounts ORDER BY id DESC'));
 if(preg_match('~^/admin/discounts/(\d+)/status$~',$route,$m)&&$method==='PATCH'){if(!one('SELECT id FROM discounts WHERE id=?',[$m[1]]))abortApi('Cupon inexistent.',404);sql('UPDATE discounts SET active=? WHERE id=?',[integer($input['active']??null,0,1),$m[1]]);respond(['ok'=>true]);}
 if(($route==='/admin/discounts'&&$method==='POST')||(preg_match('~^/admin/discounts/(\d+)$~',$route,$m)&&$method==='PUT')){$id=isset($m[1])?(int)$m[1]:null;$type=enumValue($input['type']??'',['percent','fixed']);$value=integer($input['value']??null,1,$type==='percent'?100:PHP_INT_MAX);$expires=$input['expires_at']??null;if($expires&&!strtotime($expires))abortApi('Dată invalidă.');$code=strtoupper(text($input,'code',3,50));if($id&&!one('SELECT id FROM discounts WHERE id=?',[$id]))abortApi('Cupon inexistent.',404);$duplicate=$id?one('SELECT id FROM discounts WHERE upper(code)=upper(?) AND id<>?',[$code,$id]):one('SELECT id FROM discounts WHERE upper(code)=upper(?)',[$code]);if($duplicate)abortApi('Codul cuponului este deja folosit.',409);$v=[$code,$type,$value,integer($input['min_cents']??0),($input['max_uses']??null)===null?null:integer($input['max_uses'],1),$expires,integer($input['active']??1,0,1)];if($id)sql('UPDATE discounts SET code=?,type=?,value=?,min_cents=?,max_uses=?,expires_at=?,active=? WHERE id=?',array_merge($v,[$id]));else sql('INSERT INTO discounts(code,type,value,min_cents,max_uses,expires_at,active) VALUES(?,?,?,?,?,?,?)',$v);respond(['ok'=>true]);}
 if(preg_match('~^/admin/discounts/(\d+)$~',$route,$m)&&$method==='DELETE'){if(!one('SELECT id FROM discounts WHERE id=?',[$m[1]]))abortApi('Cupon inexistent.',404);sql('DELETE FROM discounts WHERE id=?',[$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/settings'&&$method==='GET')respond(['settings'=>settingAll(),'shipping'=>all('SELECT * FROM shipping_methods'),'payments'=>paymentMethods()]);
 if($route==='/admin/settings'&&$method==='PUT'){$allowed=['seo_title','seo_description','seo_og_image','store_name','phone','email','address','low_stock_threshold'];foreach($input as $k=>$v){if(!in_array($k,$allowed)||strlen(j($v))>50000)abortApi('Setare invalidă: '.$k);if($k==='low_stock_threshold')integer($v,0,100000);elseif(!is_string($v))abortApi('Text invalid: '.$k);}tx(function()use($input){foreach($input as $k=>$v)sql('INSERT INTO settings VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value',[$k,j($v)]);});respond(['ok'=>true]);}
 if(($route==='/admin/shipping'&&$method==='POST')||(preg_match('~^/admin/shipping/(\d+)$~',$route,$m)&&$method==='PUT')){$id=isset($m[1])?(int)$m[1]:null;$v=[text($input,'name',2,100),integer($input['price_cents']??null),($input['free_threshold_cents']??null)===null?null:integer($input['free_threshold_cents']),text($input,'zones',0,500),integer($input['enabled']??0,0,1)];if($id)sql('UPDATE shipping_methods SET name=?,price_cents=?,free_threshold_cents=?,zones=?,enabled=? WHERE id=?',array_merge($v,[$id]));else sql('INSERT INTO shipping_methods(name,price_cents,free_threshold_cents,zones,enabled) VALUES(?,?,?,?,?)',$v);stripeQueue('shipping',$id??(int)db()->lastInsertId());respond(['ok'=>true]);}
 if(preg_match('~^/admin/payments/(cod|card)$~',$route,$m)&&$method==='PUT'){$enabled=integer($input['enabled']??0,0,1);if($m[1]==='card'&&$enabled&&!stripeConfigured())abortApi('Configurează cheile Stripe Floralis în .env.');$mode=$m[1]==='card'?($enabled?stripeMode():'disabled'):'local';sql('UPDATE payment_methods SET enabled=?,mode=? WHERE code=?',[$enabled,$mode,$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/pages'&&$method==='GET')respond(array_map('contentPage',all('SELECT * FROM pages ORDER BY type,id')));
 if(($route==='/admin/pages'&&$method==='POST')||(preg_match('~^/admin/pages/(\d+)$~',$route,$m)&&$method==='PUT')){$id=$route==='/admin/pages'?null:(int)$m[1];$slug=text($input,'slug',1,200);if(!preg_match('/^[a-z0-9-]+$/',$slug))abortApi('Slug invalid.');$title=text($input,'title',2,250);$body=text($input,'body',0,100000);$type=enumValue($input['type']??'page',['page','post']);$status=enumValue($input['status']??'draft',['publish','draft']);$image=text($input,'image',0,500);$seo=pageSeoDefaults(['title'=>$title,'slug'=>$slug,'body'=>$body,'type'=>$type,'status'=>$status,'image'=>$image],seoInput($input['seo']??[]));$v=[$title,$slug,$body,$type,$status,$image,j($seo)];if($id){sql('UPDATE pages SET title=?,slug=?,body=?,type=?,status=?,image=?,seo=? WHERE id=?',array_merge($v,[$id]));$savedId=$id;}else{sql('INSERT INTO pages(title,slug,body,type,status,image,seo) VALUES(?,?,?,?,?,?,?)',$v);$savedId=(int)db()->lastInsertId();}$contentKey=['despre-noi'=>'story','decor-floral'=>'decor_text'][$slug]??null;if($contentKey)sql('UPDATE settings SET value=? WHERE key=?',[j($v[2]),$contentKey]);if($v[3]==='post'&&$v[4]==='publish')announceNewsletter('post',one('SELECT * FROM pages WHERE id=?',[$savedId]));respond(['ok'=>true]);}
 if(preg_match('~^/admin/pages/(\d+)/permanent$~',$route,$m)&&$method==='DELETE'){$page=one('SELECT id,type FROM pages WHERE id=?',[$m[1]]);if(!$page)abortApi('Articol inexistent.',404);if($page['type']!=='post')abortApi('Doar articolele pot fi șterse definitiv din această secțiune.',409);sql('DELETE FROM pages WHERE id=?',[$page['id']]);respond(['ok'=>true]);}
 if(preg_match('~^/admin/pages/(\d+)$~',$route,$m)&&$method==='DELETE'){sql("UPDATE pages SET status='draft' WHERE id=?",[$m[1]]);respond(['ok'=>true]);}
 if($route==='/admin/media'&&$method==='GET')respond(all('SELECT * FROM media ORDER BY id DESC'));
 if($route==='/admin/media'&&$method==='POST'){
  $file=$_FILES['file']??null;if(!$file||$file['error']!==UPLOAD_ERR_OK||$file['size']>8*1024*1024)abortApi('Alege o imagine validă, max. 8 MB.');$info=@getimagesize($file['tmp_name']);if(!$info||!in_array($info[2],[IMAGETYPE_JPEG,IMAGETYPE_PNG,IMAGETYPE_WEBP])||$info[0]*$info[1]>25000000)abortApi('Imagine invalidă sau prea mare.');if(!function_exists('imagecreatefromstring'))abortApi('Extensia PHP GD trebuie activată pentru upload.');$img=@imagecreatefromstring(file_get_contents($file['tmp_name']));if(!$img)abortApi('Imagine invalidă.');$scale=min(1,2000/max($info[0],$info[1]));$dest=imagecreatetruecolor((int)round($info[0]*$scale),(int)round($info[1]*$scale));imagealphablending($dest,false);imagesavealpha($dest,true);imagecopyresampled($dest,$img,0,0,0,0,imagesx($dest),imagesy($dest),$info[0],$info[1]);if(!is_dir(ROOT.'/public/uploads'))mkdir(ROOT.'/public/uploads',0750,true);$name=bin2hex(random_bytes(16)).'.webp';if(!imagewebp($dest,ROOT.'/public/uploads/'.$name,85))abortApi('Imaginea nu a putut fi salvată.');$url='/uploads/'.$name;sql('INSERT INTO media(url,name,alt,uploaded) VALUES(?,?,?,1)',[$url,substr(basename($file['name']),0,200),substr($_POST['alt']??'',0,250)]);respond(['url'=>$url]);
 }
 if(preg_match('~^/admin/media/(\d+)$~',$route,$m)&&$method==='PATCH'){$alt=text($input,'alt',0,250);$media=one('SELECT * FROM media WHERE id=?',[$m[1]]);if(!$media)abortApi('Media inexistentă.',404);tx(function()use($alt,$media){sql('UPDATE media SET alt=? WHERE id=?',[$alt,$media['id']]);sql('UPDATE product_images SET alt=? WHERE url=?',[$alt,$media['url']]);});respond(['ok'=>true]);}
 if(preg_match('~^/admin/media/(\d+)$~',$route,$m)&&$method==='DELETE'){$media=one('SELECT * FROM media WHERE id=?',[$m[1]]);if(!$media)abortApi('Media inexistentă.',404);if(!$media['uploaded'])abortApi('Fișierele originale importate sunt protejate.');if(one('SELECT id FROM product_images WHERE url=?',[$media['url']])||one('SELECT id FROM categories WHERE image=?',[$media['url']])||one('SELECT id FROM pages WHERE image=?',[$media['url']])||one('SELECT key FROM settings WHERE value LIKE ?',['%'.$media['url'].'%'])||one('SELECT id FROM order_items WHERE image=?',[$media['url']]))abortApi('Imaginea este utilizată în magazin.',409);unlink(ROOT.'/public/uploads/'.basename($media['url']));sql('DELETE FROM media WHERE id=?',[$media['id']]);respond(['ok'=>true]);}
 if($route==='/admin/messages'&&$method==='GET'){
  $query=substr(trim((string)($_GET['q']??'')),0,150);$status=$_GET['status']??'';if($status!==''&&!in_array($status,['new','read','resolved'],true))abortApi('Status invalid.');
  $rows=all('SELECT m.*,(SELECT COUNT(*) FROM message_replies r WHERE r.message_id=m.id) reply_count FROM messages m ORDER BY m.id DESC');
  $rows=array_values(array_filter($rows,fn($message)=>($status===''||$message['status']===$status)&&smartSearchMatch(implode(' ',[$message['name'],$message['email'],$message['phone'],$message['subject'],$message['body']]),$query)));
  $total=count($rows);$limit=min(50,max(5,(int)($_GET['limit']??10)));$page=max(1,(int)($_GET['page']??1));$pages=max(1,(int)ceil($total/$limit));$page=min($page,$pages);$items=array_slice($rows,($page-1)*$limit,$limit);
  $items=array_map(function($message){$message['replies']=all('SELECT r.* FROM message_replies r WHERE r.message_id=? ORDER BY r.id',[$message['id']]);return $message;},$items);
  $counts=one("SELECT COUNT(*) total,SUM(CASE WHEN status='new' THEN 1 ELSE 0 END) unread,SUM(CASE WHEN status='resolved' THEN 1 ELSE 0 END) resolved FROM messages");respond(['items'=>$items,'total'=>$total,'page'=>$page,'pages'=>$pages,'counts'=>$counts]);
 }
 if(preg_match('~^/admin/messages/(\d+)/reply$~',$route,$m)&&$method==='POST'){
  $message=one('SELECT * FROM messages WHERE id=?',[$m[1]]);if(!$message)abortApi('Mesaj inexistent.',404);$subject=text($input,'subject',2,200);$body=text($input,'body',2,5000);
  $inquirySubject=$message['subject']?:'mesajul tău';$mailBody="Bună, ".$message['name']."!\n\nÎți mulțumim că ne-ai scris despre «".$inquirySubject."».\n\n".$body."\n\nCu drag,\nEchipa Floralis";$delivery=queueMail($message['email'],'Răspuns Floralis · '.$subject,$mailBody,true,'message_reply',['name'=>$message['name'],'inquiry_subject'=>$inquirySubject,'reply_subject'=>$subject,'reply_body'=>$body]);
  sql('INSERT INTO message_replies(message_id,outbox_id,subject,body,delivery_status,error) VALUES(?,?,?,?,?,?)',[$message['id'],null,$subject,$body,$delivery['status'],$delivery['error']]);$replyId=(int)db()->lastInsertId();sql("UPDATE messages SET status='resolved' WHERE id=?",[$message['id']]);respond(['ok'=>true,'delivery'=>one('SELECT delivery_status status,error FROM message_replies WHERE id=?',[$replyId])]);
 }
 if(preg_match('~^/admin/messages/(\d+)$~',$route,$m)&&$method==='GET'){$message=one('SELECT m.*,(SELECT COUNT(*) FROM message_replies r WHERE r.message_id=m.id) reply_count FROM messages m WHERE m.id=?',[$m[1]]);if(!$message)abortApi('Mesaj inexistent.',404);$message['replies']=all('SELECT r.* FROM message_replies r WHERE r.message_id=? ORDER BY r.id',[$message['id']]);respond($message);}
 if($route==='/admin/newsletter'&&$method==='GET'){
  $query=substr(trim((string)($_GET['q']??'')),0,150);$rows=all('SELECT * FROM newsletter ORDER BY id DESC');$filtered=array_values(array_filter($rows,fn($subscriber)=>smartSearchMatch($subscriber['email'],$query)));
  $total=count($filtered);$limit=min(50,max(5,(int)($_GET['limit']??10)));$page=max(1,(int)($_GET['page']??1));$pages=max(1,(int)ceil($total/$limit));$page=min($page,$pages);$now=time();$today=date('Y-m-d');
  $counts=['total'=>count($rows),'recent'=>count(array_filter($rows,fn($subscriber)=>strtotime($subscriber['consent_at'])>=$now-30*86400)),'today'=>count(array_filter($rows,fn($subscriber)=>str_starts_with($subscriber['consent_at'],$today)))];
  respond(['items'=>array_slice($filtered,($page-1)*$limit,$limit),'total'=>$total,'page'=>$page,'pages'=>$pages,'counts'=>$counts]);
 }
 if($route==='/admin/reviews'&&$method==='GET')respond(all('SELECT * FROM reviews ORDER BY id DESC LIMIT 1000'));
 if(preg_match('~^/admin/messages/(\d+)$~',$route,$m)&&$method==='PATCH'){sql('UPDATE messages SET status=? WHERE id=?',[enumValue($input['status']??'',['new','read','resolved']),$m[1]]);respond(['ok'=>true]);}
 if(preg_match('~^/admin/reviews/(\d+)$~',$route,$m)&&$method==='PATCH'){sql('UPDATE reviews SET approved=? WHERE id=?',[integer($input['approved']??0,0,1),$m[1]]);if(isset($input['reply']))sql("UPDATE reviews SET reply=?,replied_at=datetime('now') WHERE id=?",[text($input,'reply',0,3000),$m[1]]);respond(['ok'=>true]);}
 if(preg_match('~^/admin/reviews/(\d+)$~',$route,$m)&&$method==='DELETE'){sql('DELETE FROM reviews WHERE id=?',[$m[1]]);respond(['ok'=>true]);}
 if(preg_match('~^/admin/export/(orders|newsletter|products|customers)$~',$route,$m)&&$method==='GET'){$queries=['orders'=>"SELECT number,status,payment_method,payment_status,shipping_method,delivery_time_slot,total_cents,created_at FROM orders WHERE payment_method!='card' OR payment_status='paid'",'newsletter'=>'SELECT email,consent_at FROM newsletter','products'=>'SELECT sku,name,slug,price_cents,stock,status FROM products','customers'=>'SELECT name,email,phone,created_at FROM customers'];$rows=all($queries[$m[1]]);header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="floralis-'.$m[1].'.csv"');echo "\xEF\xBB\xBF";$f=fopen('php://output','w');if($rows){fputcsv($f,array_keys($rows[0]),',','"','');foreach($rows as $r)fputcsv($f,array_map(fn($v)=>preg_match('/^[=+@-]/',(string)$v)?"'".$v:$v,$r),',','"','');}exit;}
 abortApi('Endpoint inexistent.',404);
}catch(PDOException $e){if(str_contains($e->getMessage(),'UNIQUE constraint'))respond(['error'=>'Acest slug sau cod există deja.'],409);error_log('Floralis DB: '.$e->getMessage());respond(['error'=>'Operația nu a reușit. Încearcă din nou.'],500);}catch(Throwable $e){$code=$e->getCode();if($code>=400&&$code<=499)respond(['error'=>$e->getMessage()],$code);error_log('Floralis: '.$e->getMessage());respond(['error'=>'Operația nu a reușit. Încearcă din nou.'],500);}
