<?php
declare(strict_types=1);
function googleConfig(): ?array {$file=env('GOOGLE_CREDENTIALS_FILE','data/google-client.json');if(!preg_match('~^(?:[A-Z]:|/)~i',$file))$file=ROOT.'/'.$file;if(!is_file($file))return null;$d=decoded(file_get_contents($file));$c=$d['web']??null;return !empty($c['client_id'])&&!empty($c['client_secret'])?$c:null;}
function googleStatus(): array {$c=googleConfig();return ['configured'=>(bool)$c,'enabled'=>(bool)$c&&env('GOOGLE_LOCAL_CALLBACK_ENABLED','0')==='1'];}
function googleHttp(string $url,?array $post=null): array {
 if(!function_exists('curl_init'))abortApi('Activează extensia PHP cURL pentru Google OAuth.',503);
 $c=curl_init($url);$options=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2];if(defined('CURLSSLOPT_NATIVE_CA'))$options[CURLOPT_SSL_OPTIONS]=CURLSSLOPT_NATIVE_CA;if($post){$options[CURLOPT_POST]=true;$options[CURLOPT_POSTFIELDS]=http_build_query($post);}$ca=env('CURL_CA_BUNDLE');if($ca)$options[CURLOPT_CAINFO]=$ca;curl_setopt_array($c,$options);$body=curl_exec($c);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);if($body===false||$status!==200)abortApi('Autentificarea Google nu a putut fi verificată.',502);$data=json_decode($body,true);if(!is_array($data))abortApi('Răspuns Google invalid.',502);return $data;
}
function decode64(string $s): string|false {return base64_decode(strtr($s,'-_','+/'),true);}
function googleIdentity(string $jwt,array $client,string $nonce): array {
 $parts=explode('.',$jwt);if(count($parts)!==3)abortApi('Token Google invalid.',401);$header=json_decode(decode64($parts[0])?:'',true);$claims=json_decode(decode64($parts[1])?:'',true);$signature=decode64($parts[2]);if(!is_array($header)||!is_array($claims)||($header['alg']??'')!=='RS256'||!isset($header['kid'])||!$signature)abortApi('Token Google invalid.',401);
 $cache=ROOT.'/data/google-certs.json';$saved=is_file($cache)?decoded(file_get_contents($cache)):[];if(($saved['expires']??0)<time()||empty($saved['certs'][$header['kid']])){$saved=['expires'=>time()+600,'certs'=>googleHttp('https://www.googleapis.com/oauth2/v1/certs')];file_put_contents($cache,j($saved),LOCK_EX);}
 $cert=$saved['certs'][$header['kid']]??null;if(!$cert||!function_exists('openssl_verify')||openssl_verify($parts[0].'.'.$parts[1],$signature,$cert,OPENSSL_ALGO_SHA256)!==1)abortApi('Semnătura Google este invalidă.',401);
 if(!in_array($claims['iss']??'',['https://accounts.google.com','accounts.google.com'],true)||($claims['aud']??'')!==$client['client_id']||($claims['exp']??0)<time()||($claims['iat']??0)>time()+60||($claims['nonce']??'')!==$nonce||empty($claims['sub'])||($claims['email_verified']??false)!==true||!filter_var($claims['email']??'',FILTER_VALIDATE_EMAIL)||(!empty($claims['azp'])&&$claims['azp']!==$client['client_id']))abortApi('Identitatea Google nu a putut fi validată.',401);return $claims;
}
function googleRoute(string $route,string $key): never {
 try {
  $c=googleConfig();if(!$c||!googleStatus()['enabled'])abortApi('Adaugă callback-ul local în Google Cloud și activează GOOGLE_LOCAL_CALLBACK_ENABLED în .env.',503);
  $redirect=rtrim(env('APP_URL','http://localhost:5173'),'/').'/api/auth/google/callback';
  if($route==='/auth/google/start'){$state=bin2hex(random_bytes(24));$nonce=bin2hex(random_bytes(24));$verifier=rtrim(strtr(base64_encode(random_bytes(48)),'+/','-_'),'=');sql('DELETE FROM oauth_states WHERE expires_at<?',[(int)(microtime(true)*1000)]);sql('INSERT INTO oauth_states VALUES(?,?,?,?,?)',[hash('sha256',$state),$key,$nonce,$verifier,(int)(microtime(true)*1000)+600000]);$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');$url='https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(['client_id'=>$c['client_id'],'redirect_uri'=>$redirect,'response_type'=>'code','scope'=>'openid email profile','state'=>$state,'nonce'=>$nonce,'code_challenge'=>$challenge,'code_challenge_method'=>'S256','prompt'=>'select_account']);header('Location: '.$url, true,302);exit;}
  $state=$_GET['state']??'';$pending=tx(function()use($state,$key){$pending=one('SELECT * FROM oauth_states WHERE state_hash=? AND session_hash=? AND expires_at>?',[hash('sha256',$state),$key,(int)(microtime(true)*1000)]);if(!$pending)abortApi('Sesiune Google invalidă sau expirată.',401);sql('DELETE FROM oauth_states WHERE state_hash=?',[$pending['state_hash']]);return $pending;});if(!empty($_GET['error'])||empty($_GET['code']))abortApi('Autentificarea Google a fost anulată.',401);
  $tokens=googleHttp('https://oauth2.googleapis.com/token',['client_id'=>$c['client_id'],'client_secret'=>$c['client_secret'],'code'=>$_GET['code'],'grant_type'=>'authorization_code','redirect_uri'=>$redirect,'code_verifier'=>$pending['verifier']]);$identity=googleIdentity($tokens['id_token']??'',$c,$pending['nonce']);
  $u=tx(function()use($identity){$bound=one("SELECT u.* FROM users u JOIN oauth_identities o ON o.user_id=u.id WHERE o.provider='google' AND o.subject=?",[$identity['sub']]);if($bound){if(!$bound['active']||$bound['role']==='admin')abortApi('Acces indisponibil.',403);return $bound;}$u=one('SELECT * FROM users WHERE email=?',[strtolower($identity['email'])]);if($u&&(!$u['active']||$u['role']==='admin'))abortApi('Contul administratorului folosește autentificarea proprie.',403);if(!$u){sql('INSERT INTO users(email,password_hash,name) VALUES(?,?,?)',[strtolower($identity['email']),password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT),substr($identity['name']??$identity['email'],0,100)]);$u=one('SELECT * FROM users WHERE id=?',[(int)db()->lastInsertId()]);}sql("INSERT INTO oauth_identities(user_id,provider,subject) VALUES(?,'google',?)",[$u['id'],$identity['sub']]);return $u;});
  $raw=bin2hex(random_bytes(32));$new=hash('sha256',$raw);tx(function()use($u,$new,$key){sql('INSERT INTO sessions VALUES(?,?,?,?)',[$new,$u['id'],bin2hex(random_bytes(24)),(int)(microtime(true)*1000)+604800000]);sql('UPDATE cart_items SET session_hash=? WHERE session_hash=?',[$new,$key]);sql('DELETE FROM sessions WHERE token_hash=?',[$key]);});setcookie(env('SESSION_COOKIE','floralis_session'),$raw,['expires'=>time()+604800,'path'=>'/','httponly'=>true,'samesite'=>'Lax','secure'=>str_starts_with(env('APP_URL'),'https://')]);header('Location: /cont',true,302);exit;
 }catch(Throwable $e){error_log('Floralis Google OAuth: '.($e->getCode()?:500));header('Location: /cont?google=error',true,302);exit;}
}
