<?php
require __DIR__.'/../app/bootstrap.php';migrate();
$data=decoded(file_get_contents(ROOT.'/data/floralis_catalog.json'));$content=decoded(file_get_contents(ROOT.'/data/floralis_content.json'));
tx(function()use($data,$content){
 $initialFeatured=['4','12','13','17','27','36','43','49','51','56','58','61','63','65','67','69','75'];
 foreach($data['categories'] as $c){$parent=$c['parent_slug']?one('SELECT id FROM categories WHERE slug=?',[$c['parent_slug']]):null;sql('INSERT OR IGNORE INTO categories(name,slug,parent_id) VALUES(?,?,?)',[$c['name'],$c['slug'],$parent['id']??null]);}
 foreach($data['products'] as $p){if(one('SELECT id FROM products WHERE source_id=?',[$p['source_id']]))continue;$p['featured']=in_array((string)($p['sku']??''),$initialFeatured,true)?1:(int)($p['featured']??0);$fields=['source_id','sku','name','slug','status','price_cents','regular_price_cents','sale_price_cents','stock','stock_status','manage_stock','featured','description','short_description','tax_status','tax_class'];$values=array_map(fn($k)=>$p[$k]??null,$fields);$values[]=j($p['source_fields']);sql('INSERT INTO products('.implode(',',$fields).',source_fields) VALUES('.implode(',',array_fill(0,count($values),'?')).')',$values);$id=(int)db()->lastInsertId();foreach($p['categories'] as $slug){$cat=one('SELECT id FROM categories WHERE slug=?',[$slug]);if($cat)sql('INSERT OR IGNORE INTO product_categories VALUES(?,?)',[$id,$cat['id']]);}foreach($p['images'] as $i)sql('INSERT INTO product_images(product_id,url,alt,sort_order,original_url) VALUES(?,?,?,?,?)',[$id,$i['url'],$i['alt'],$i['sort_order'],$i['original_url']]);}
 $selected=['nunta'=>'22','botez'=>'38','aranjamente-florale'=>'4','cadouri-accesorii'=>'58','craciun'=>'75'];
 foreach(categories() as $c)if(!$c['image']){foreach($data['products'] as $p)if(in_array($c['slug'],$p['categories'])&&(!isset($selected[$c['slug']])||$p['sku']===$selected[$c['slug']])){sql('UPDATE categories SET image=? WHERE id=?',[$p['images'][0]['url']??'',$c['id']]);break;}}
 foreach($data['media'] as $m)sql('INSERT OR IGNORE INTO media(url,name,alt,type) VALUES(?,?,?,?)',[$m['url'],$m['name'],$m['alt'],$m['type']]);
 $wanted=['despre-noi','decor-floral','contact','termeni-si-conditii','transport-si-livrare','modalitati-de-plata','alergeni'];
 foreach($data['pages'] as $p)if(in_array($p['slug'],$wanted)||str_starts_with($p['slug'],'lorem-ipsum'))sql('INSERT OR IGNORE INTO pages(slug,title,body,type,status) VALUES(?,?,?,?,?)',[$p['slug'],$p['title'],$p['body'],str_starts_with($p['slug'],'lorem-ipsum')?'post':'page',str_starts_with($p['slug'],'lorem-ipsum')?'draft':'publish']);
 $extras=[['confidentialitate','Politica de confidențialitate','Datele introduse în cont, adresă, comandă sau formular sunt păstrate în baza de date locală Floralis. Contact pentru informații privind datele personale: floralis.artaflorilor@yahoo.com. Politica completă pentru magazinul public trebuie completată înainte de publicare.'],['cookies','Politica de cookies','Aplicația folosește un cookie necesar pentru sesiune, autentificare și coș. Nu sunt activate servicii de analiză sau publicitate. Preferințele de navigare se păstrează local pe dispozitiv.'],['retur','Retur și retragere','Condițiile de retur disponibile în export sunt cuprinse în Termeni și condiții. Pentru informații referitoare la un produs, contactează Floralis la 0720 823 194 sau floralis.artaflorilor@yahoo.com.'],['gdpr','Date personale / GDPR','Pentru întrebări privind datele personale, folosește floralis.artaflorilor@yahoo.com. Informațiile originale sunt disponibile în Termeni și condiții.']];
 foreach($extras as $p)sql('INSERT OR IGNORE INTO pages(slug,title,body) VALUES(?,?,?)',$p);
 $testPost=['din-culisele-floralis-cum-prinde-viata-un-decor-floral','Din culisele Floralis: cum prinde viață un decor floral',"Totul începe cu o stare. Uneori este liniștea unei grădini la apus, alteori energia unei seri în care oamenii dragi se întâlnesc. Înainte să alegem florile, ascultăm povestea și căutăm acel fir care leagă locul, lumina și emoția.\n\nPRIMUL GÂND DEVINE DIRECȚIE\n\nMoodboardul adună nuanțe, texturi, volume și mici detalii de atmosferă. Nu este doar o colecție de imagini, ci harta după care construim fiecare alegere. De aici se nasc paleta cromatică, ritmul meselor și felul în care florile vor locui în spațiu.\n\nFLORILE SUNT ALESE CU INTENȚIE\n\nFiecare soi are un rol. Unele flori dau structură, altele aduc mișcare, transparență sau parfum. Alegem prospețimea, proporția și felul în care fiecare tulpină se așază lângă celelalte, pentru ca rezultatul să pară firesc și viu.\n\n> Un decor reușit nu acoperă spațiul. Îl face să spună povestea oamenilor care îl locuiesc.\n\nATELIERUL: LOCUL ÎN CARE IDEEA CAPĂTĂ FORMĂ\n\nÎn atelier testăm compoziții, ajustăm înălțimi și urmărim cum se schimbă florile în lumină. Fiecare aranjament este construit manual, iar detaliile mici — o panglică, o ramură curbată, o lumânare — dau coerență întregului univers.\n\nZIUA MONTAJULUI\n\nLa locație, totul prinde viață. Lucrăm în ritmul spațiului, adaptăm piesele și ne asigurăm că fiecare perspectivă este frumoasă: intrarea, mesele, ceremonia și locurile în care se vor păstra cele mai multe amintiri.\n\nFRUMOSUL CARE RĂMÂNE\n\nCând luminile se aprind și invitații sosesc, decorul nu mai este doar al nostru. Devine fundalul unei povești reale. Aceasta este partea pe care o iubim cel mai mult: clipa în care munca din atelier se transformă în emoție.",'post','publish','/assets/floralis/export-cd0301132119.webp',j(['title'=>'Cum prinde viață un decor floral · Jurnal Floralis','description'=>'Din culisele atelierului Floralis: moodboard, alegerea florilor, pregătirea și montajul unui decor floral personalizat.','canonical'=>'','og_image'=>'/assets/floralis/export-cd0301132119.webp','noindex'=>false])];
 sql('INSERT OR IGNORE INTO pages(slug,title,body,type,status,image,seo) VALUES(?,?,?,?,?,?,?)',$testPost);
 $settings=['store_name'=>'Floralis — arta florilor','phone'=>'0720823194','email'=>'floralis.artaflorilor@yahoo.com','address'=>'Calea București Nr. 9, Tunari, Ilfov','hero_title'=>'Mai mult decât flori,','hero_emphasis'=>'emoții în dar.','hero_text'=>'Aranjamente florale create cu pasiune pentru cele mai frumoase momente din viața ta.','hero_image'=>'/assets/floralis/product-4163-0.webp','hero_images'=>['/assets/floralis/product-4163-0.webp','/assets/floralis/product-4164-0.webp','/assets/floralis/product-4159-0.webp'],'collection_slugs'=>['nunta','botez','aranjamente-florale','cadouri-accesorii','craciun'],'recommended_skus'=>['4','12','13','16'],'story'=>$content['about'],'decor_text'=>$content['decor'],'gallery'=>$content['gallery'],'social'=>$content['social'],'newsletter_title'=>'Un strop de inspirație, în inboxul tău.','newsletter_text'=>'Colecții noi, povești din atelier și idei pentru momentele care contează.','low_stock_threshold'=>5];
 foreach($settings as $k=>$v)sql('INSERT OR IGNORE INTO settings VALUES(?,?)',[$k,j($v)]);
 if(!one('SELECT id FROM shipping_methods LIMIT 1')){sql('INSERT INTO shipping_methods(name,price_cents,enabled) VALUES(?,?,?)',['Ridicare din florărie',0,1]);sql('INSERT INTO shipping_methods(name,price_cents,zones,enabled) VALUES(?,?,?,?)',['Livrare locală',0,'Ilfov,București',0]);}
 sql("INSERT OR IGNORE INTO payment_methods VALUES('cod','Ramburs / plată la ridicare',1,'local')");sql("INSERT OR IGNORE INTO payment_methods VALUES('card','Card bancar',0,'disabled')");
 sql("INSERT OR IGNORE INTO newsletter_campaigns(entity_type,entity_id) SELECT 'product',id FROM products WHERE status='publish'");
 sql("INSERT OR IGNORE INTO newsletter_campaigns(entity_type,entity_id) SELECT 'post',id FROM pages WHERE type='post' AND status='publish'");
 $mail=env('ADMIN_EMAIL');$pass=env('ADMIN_PASSWORD');if($mail&&$pass){$admin=one('SELECT * FROM users WHERE email=?',[$mail]);if(!$admin)sql("INSERT INTO users(email,password_hash,name,role) VALUES(?,?,?,'admin')",[$mail,password_hash($pass,PASSWORD_DEFAULT),'Administrator Floralis']);elseif(str_contains($admin['password_hash'],':'))sql('UPDATE users SET password_hash=? WHERE id=?',[password_hash($pass,PASSWORD_DEFAULT),$admin['id']]);}
});echo 'Floralis seed: '.j(['products'=>one('SELECT COUNT(*) n FROM products')['n'],'categories'=>one('SELECT COUNT(*) n FROM categories')['n']])."\n";
