import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Leaf,Heart,Diamond,Star,Quote} from 'lucide-react';
import {useStore} from './context';
import {api} from './api';
import {Image,USP,SectionHeading,ProductCard,Newsletter} from './components';
export default function Home(){const s=useStore(),settings=s.data?.settings,[slide,setSlide]=useState(0),[products,setProducts]=useState([]),imageCount=settings?.hero_images?.length||1;useEffect(()=>{api('/products?limit=100').then(r=>setProducts(r.items)).catch(e=>s.notify(e.message,'error'));},[]);useEffect(()=>{setSlide(0);if(imageCount<2||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;const id=setInterval(()=>setSlide(v=>(v+1)%imageCount),7000);return()=>clearInterval(id);},[imageCount]);if(!settings)return null;const collections=settings.collection_slugs.map(slug=>s.data.categories.find(c=>c.slug===slug)).filter(Boolean),recommended=products.filter(p=>settings.recommended_skus.includes(p.sku)).slice(0,4),story=settings.story?.split('\n').filter(Boolean).find(x=>x.startsWith('Floralis'));
return <><section className="hero"><div className="hero-photo"><Image key={slide} src={settings.hero_images?.[slide]||settings.hero_image} alt="Buchet de mireasă Floralis, în nuanțe pastelate" priority/><div className="hero-arc"/></div><div className="hero-copy"><span className="eyebrow dark">FLORI PENTRU<br/>MOMENTE CARE CONTEAZĂ</span><h1>{settings.hero_title.includes(' decât ')?<>{settings.hero_title.split(' decât ')[0]}<br/>decât {settings.hero_title.split(' decât ').slice(1).join(' decât ')}</>:settings.hero_title}<br/><em>{settings.hero_emphasis}</em></h1><p>{settings.hero_text}</p><div className="hero-actions"><Link className="gold-button" to="/magazin">Descoperă colecțiile<ArrowRight size={20}/></Link><Link className="text-link secondary-hero" to="/decor-floral">Decor floral</Link></div><USP/></div><div className="hero-signature">ARTĂ<br/>EMOȚIE<br/>ELEGANȚĂ<i/></div><div className="hero-slides"><i/>{Array.from({length:imageCount},(_,n)=>n).map(n=><button key={n} onClick={()=>setSlide(n)} className={slide===n?'active':''} aria-label={'Fotografia '+(n+1)} aria-pressed={slide===n}>{String(n+1).padStart(2,'0')}</button>)}</div></section>
<section className="collections-section section reveal"><SectionHeading eyebrow="DESCOPERĂ" title="Colecțiile noastre" link="/magazin" label="Vezi toate categoriile"/><div className="collections">{collections.map((c,i)=><Link key={c.id} to={'/categorie/'+c.slug} className={'collection-card collection-'+i}><div><h3>{c.name==='Nunta'?'Nuntă':c.name==='Craciun'?'Crăciun':c.name}</h3><p>{['Aranjamente de poveste','Purețe și delicatețe','Pentru orice ocazie','Detalii care fac diferența','Magia sărbătorilor'][i]}</p></div><Image src={c.image} alt={c.name}/><span className="round-arrow"><ArrowRight size={17}/></span></Link>)}</div></section>
<section className="floral-banner reveal"><span className="eyebrow">FLORALIS</span><h2>Frumusețea naturală<br/><em>în fiecare detaliu</em></h2><i/></section>
<section className="decor-home section reveal"><div className="decor-home-images"><Image src={settings.gallery[8]?.url||settings.gallery[0]?.url} alt="Decor floral pentru evenimente"/><Image className="decor-inset" src={settings.gallery[18]?.url||settings.gallery[1]?.url} alt="Detaliu dintr-un decor Floralis"/><span>DIN ATELIER, CU SUFLET</span></div><div className="editorial-copy"><span className="eyebrow">O POVESTE ÎNFLORITĂ</span><h2>Decor floral pentru<br/><em>momente memorabile.</em></h2><p>Transformăm momentele speciale în amintiri de neuitat. Botezuri, aniversări, evenimente corporate, cu atenție la detalii și flori proaspete.</p><p>Spune-ne povestea ta, noi o înflorim!</p><Link className="gold-button" to="/decor-floral">Descoperă serviciile<ArrowRight size={18}/></Link><Link className="text-link" to="/contact?subiect=Ofertă decor floral">Solicită ofertă</Link></div></section>
<section className="section reveal"><SectionHeading eyebrow="ALESE CU GRIJĂ" title="Un dar, o emoție, o poveste" link="/magazin" label="Descoperă magazinul"/><div className="product-grid">{recommended.map(p=><ProductCard key={p.id} p={p}/>)}</div></section>
<section className="occasions section reveal"><span className="eyebrow">FIECARE MOMENT MERITĂ FLORI</span><h2>Pentru toate felurile de <em>„te iubesc”.</em></h2><div>{[['Aniversări','aranjamente-florale'],['Ziua nunții','nunta'],['Bun venit pe lume','botez'],['Un simplu „mulțumesc”','cadouri-accesorii']].map(([name,slug])=><Link to={'/categorie/'+slug} key={slug}>{name}<ArrowRight size={17}/></Link>)}</div></section>
<section className="story section reveal"><div className="editorial-copy"><span className="eyebrow">POVESTEA NOASTRĂ</span><h2>Mai mult decât un atelier.<br/><em>Un loc pentru frumos.</em></h2><p>{story}</p><Link className="text-link" to="/despre-noi">Cunoaște-ne<ArrowRight size={18}/></Link><div className="story-number">2017<span>De atunci, înflorim povești.</span></div></div><Image src={settings.gallery[23]?.url||settings.gallery[0]?.url} alt="Creație florală din atelierul Floralis"/></section>
<section className="why-floralis section reveal"><SectionHeading eyebrow="PROMISIUNEA NOASTRĂ" title="Cu grijă. Cu pasiune. Cu suflet."/><div className="values">{[[Leaf,'Prospețime în fiecare petală','Alegem cu grijă florile, texturile și combinațiile cromatice.'],[Diamond,'Atenție la fiecare detaliu','Fiecare creație are un aer natural, rafinat și armonios.'],[Heart,'Emoții care rămân','Fiecare comandă spune o poveste și merită creată cu suflet.']].map(([Icon,title,text])=><article key={title}><Icon strokeWidth={1}/><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section className="section gallery-home reveal"><SectionHeading eyebrow="DIN LUMEA FLORALIS" title="Puțină inspirație pentru suflet" link="/galerie" label="Vezi galeria"/><div>{settings.gallery.slice(0,4).map((g,i)=><Link to="/galerie" key={g.url}><Image src={g.url} alt={'Decor floral Floralis '+(i+1)}/></Link>)}</div></section>
<section className="testimonials section reveal"><Quote size={30} strokeWidth={1}/><span className="eyebrow">POVEȘTI CARE NE BUCURĂ</span>{s.data.reviews.length?<div className="reviews">{s.data.reviews.map((r,i)=><blockquote key={i}><div>{Array.from({length:r.rating},(_,n)=><Star key={n} size={14}/>)}</div><p>„{r.body}”</p><cite>{r.name}</cite></blockquote>)}</div>:<><h2>Ai o poveste cu Floralis?</h2><p>Ne bucurăm să aflăm ce au însemnat florile noastre pentru tine.</p><Link className="text-link" to="/cont?tab=recenzie">Împărtășește experiența ta<ArrowRight size={17}/></Link></>}</section><Newsletter/></>;}
