import React,{Suspense,lazy,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,useLocation} from 'react-router-dom';
import '@fontsource/cormorant-garamond/latin-ext-400.css';
import '@fontsource/cormorant-garamond/latin-ext-500.css';
import '@fontsource/cormorant-garamond/latin-ext-400-italic.css';
import '@fontsource/inter/latin-ext-400.css';
import '@fontsource/inter/latin-ext-500.css';
import '@fontsource/inter/latin-ext-600.css';
import './styles.css';
import './storefront-chrome.css';
import './collections.css';
import './decor-home.css';
import './product-cards.css';
import './recommended-carousel.css';
import './story-home.css';
import './home-sections.css';
import './home-gallery.css';
import './search-dialog.css';
import './visit-home.css';
import './newsletter.css';
import './footer.css';
import './mobile-nav.css';
import './cart-favorites.css';
import './auth.css';
import './gallery-page.css';
import './about-page.css';
import './decor-page.css';
import './contact-premium.css';
import './account-premium.css';
import './info-pages.css';
import './blog-premium.css';
import './whatsapp.css';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/cormorant-garamond/latin-500.css';
import '@fontsource/cormorant-garamond/latin-400-italic.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import {StoreProvider,useStore} from './context';
import {Header,Footer,CartDrawer,RevealObserver,WhatsAppButton} from './components';
import Home from './Home';
const Pages=lazy(()=>import('./Pages'));
const Admin=lazy(()=>import('./Admin'));
function PageTitle(){const loc=useLocation(),s=useStore();useEffect(()=>{const root=document.getElementById('root'),titles={'/':'Florărie online Tunari & București | Floralis','/magazin':'Flori și aranjamente florale online | Floralis','/decor-floral':'Decor floral pentru nunți și evenimente | Floralis','/despre-noi':'Despre Floralis | Florărie și atelier floral Tunari','/contact':'Contact Floralis | Florărie în Tunari, Ilfov','/galerie':'Galerie aranjamente și decoruri florale | Floralis','/blog':'Sfaturi și povești despre flori | Blog Floralis','/faq':'Întrebări frecvente despre comenzi și flori | Floralis','/transport-si-livrare':'Livrare flori în Tunari, Ilfov și București | Floralis','/modalitati-de-plata':'Plată online sigură și ramburs | Floralis','/alergeni':'Alergeni și informații despre produse | Floralis','/termeni-si-conditii':'Termeni și condiții magazin online | Floralis','/confidentialitate':'Politica de confidențialitate | Floralis','/cookies':'Politica de cookies | Floralis','/retur':'Retur și retragere din comandă | Floralis','/gdpr':'Protecția datelor personale și GDPR | Floralis'};const update=()=>{const heading=root.querySelector('h1')?.innerText?.replace(/\s+/g,' ').trim();document.title=loc.pathname==='/'?(s.data?.settings?.seo_title||titles['/']):titles[loc.pathname]||(heading?heading+' | Floralis':'Floralis — arta florilor');};update();const observer=new MutationObserver(update);observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect();},[loc.pathname,s.data]);return null;}
function ScrollToAnchor(){const loc=useLocation();useEffect(()=>{if(!loc.hash)return;let observer=null,timeout=0,frame=0,innerFrame=0,stopped=false;let id='';try{id=decodeURIComponent(loc.hash.slice(1));}catch{id=loc.hash.slice(1);}const scroll=()=>{const target=document.getElementById(id);if(!target)return false;frame=requestAnimationFrame(()=>{innerFrame=requestAnimationFrame(()=>{if(!stopped)target.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});});return true;};if(!scroll()){const root=document.getElementById('root');observer=new MutationObserver(()=>{if(scroll())observer?.disconnect();});if(root)observer.observe(root,{childList:true,subtree:true});timeout=window.setTimeout(()=>observer?.disconnect(),5000);}return()=>{stopped=true;observer?.disconnect();window.clearTimeout(timeout);cancelAnimationFrame(frame);cancelAnimationFrame(innerFrame);};},[loc.pathname,loc.search,loc.hash]);return null;}
function App(){const loc=useLocation(),s=useStore();const admin=loc.pathname.startsWith('/admin');return <><RevealObserver/>{admin?<Suspense fallback={<div className="loading">Se încarcă atelierul…</div>}><Admin/></Suspense>:<div className="storefront"><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="*" element={<Suspense fallback={<div className="loading">Se încarcă…</div>}><Pages/></Suspense>}/></Routes></main><Footer/><CartDrawer/><WhatsAppButton/></div>}{!s.data&&<div className="loading">Pregătim florile pentru tine…</div>}</>;}
createRoot(document.getElementById('root')).render(<BrowserRouter><StoreProvider><PageTitle/><ScrollToAnchor/><App/></StoreProvider></BrowserRouter>);
