import React,{Suspense,lazy,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,useLocation} from 'react-router-dom';
import '@fontsource/cormorant-garamond/latin-ext-400.css';
import '@fontsource/cormorant-garamond/latin-ext-500.css';
import '@fontsource/cormorant-garamond/latin-ext-400-italic.css';
import '@fontsource/inter/latin-ext-400.css';
import '@fontsource/inter/latin-ext-500.css';
import '@fontsource/inter/latin-ext-600.css';
import './styles.css';
import './storefront-chrome.css';
import './collections.css';
import './decor-home.css';
import './product-cards.css';
import './recommended-carousel.css';
import './story-home.css';
import './home-sections.css';
import './home-gallery.css';
import './search-dialog.css';
import './visit-home.css';
import './newsletter.css';
import '@fontsource/cormorant-garamond/latin-400.css';
import '@fontsource/cormorant-garamond/latin-500.css';
import '@fontsource/cormorant-garamond/latin-400-italic.css';
import '@fontsource/inter/latin-400.css';
import '@fontsource/inter/latin-500.css';
import '@fontsource/inter/latin-600.css';
import {StoreProvider,useStore} from './context';
import {Header,Footer,CartDrawer,RevealObserver} from './components';
import Home from './Home';
const Pages=lazy(()=>import('./Pages'));
const Admin=lazy(()=>import('./Admin'));
function PageTitle(){const loc=useLocation(),s=useStore();useEffect(()=>{const root=document.getElementById('root');const update=()=>{const heading=root.querySelector('h1')?.innerText?.replace(/\s+/g,' ').trim();document.title=loc.pathname==='/'?(s.data?.settings?.seo_title||'Floralis — arta florilor'):heading?heading+' · Floralis':'Floralis — arta florilor';};update();const observer=new MutationObserver(update);observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect();},[loc.pathname,s.data]);return null;}
function App(){const loc=useLocation(),s=useStore();const admin=loc.pathname.startsWith('/admin');return <><RevealObserver/>{admin?<Suspense fallback={<div className="loading">Se încarcă atelierul…</div>}><Admin/></Suspense>:<div className="storefront"><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="*" element={<Suspense fallback={<div className="loading">Se încarcă…</div>}><Pages/></Suspense>}/></Routes></main><Footer/><CartDrawer/></div>}{!s.data&&<div className="loading">Pregătim florile pentru tine…</div>}</>;}
createRoot(document.getElementById('root')).render(<BrowserRouter><StoreProvider><PageTitle/><App/></StoreProvider></BrowserRouter>);
